# ABSTRACT: Driver for the Finnish tagset from the Turku Dependency Treebank.
# Tag is a sequence of features separated by vertical bars. There are just the feature values, not attribute-value pairs.
# Copyright © 2011, 2014 Dan Zeman <zeman@ufal.mff.cuni.cz>

package Lingua::Interset::Tagset::FI::Turku;
use strict;
use warnings;
# VERSION: generated by DZP::OurPkgVersion

use utf8;
use open ':utf8';
use namespace::autoclean;
use Moose;
extends 'Lingua::Interset::Tagset';



has 'features_all' => ( isa => 'ArrayRef', is => 'ro', builder => '_create_features_all', lazy => 1 );
has 'atoms' => ( isa => 'HashRef', is => 'ro', builder => '_create_atoms', lazy => 1 );



#------------------------------------------------------------------------------
# Returns the tagset id that should be set as the value of the 'tagset' feature
# during decoding. Every derived class must (re)define this method! The result
# should correspond to the last two parts in package name, lowercased.
# Specifically, it should be the ISO 639-2 language code, followed by '::' and
# a language-specific tagset id. Example: 'cs::multext'.
#------------------------------------------------------------------------------
sub get_tagset_id
{
    return 'fi::turku';
}



#------------------------------------------------------------------------------
# Creates the list of all surface features that can appear in the tag.
#------------------------------------------------------------------------------
sub _create_features_all
{
    my $self = shift;
    my @features = ('pos', 'abbr', 'foreign', 'prop', 'prontype', 'numtype', 'copula', 'advtype', 'conjtype', 'punctype',
                    'degree', 'case', 'number', 'poss', 'mood', 'tense', 'voice', 'person', 'neg', 'inf', 'pcp', 'clitic',
                    'style', 'up', 'trunco', 'unknown');
    return \@features;
}



#------------------------------------------------------------------------------
# Creates atomic drivers for surface features.
#------------------------------------------------------------------------------
sub _create_atoms
{
    my $self = shift;
    my %atoms;
    # PART OF SPEECH ####################
    # Some tags contain two parts of speech, e.g. C|...|V. The rightmost is probably the POS of the stem,
    # while the leftmost one is the resulting POS on the surface. In the list of known tags, I removed the rightmost tag.
    # Some tags do not contain any part of speech, e.g. the DV-MA derivations.
    # http://en.wiktionary.org/wiki/-ma#Finnish hints that the result can be either noun or verb.
    # I added "N" to all "DV-MA" tags in the list of known tags.
    $atoms{pos} = $self->create_atom
    (
        'tagset' => 'fi::turku',
        'surfeature' => 'pos',
        'decode_map' =>
        {
            'A'     => ['pos' => 'adj'],
            # see e.g. http://archives.conlang.info/pei/juenchen/phaelbhaduen.html for what ad-adjective is
            'AD-A'  => ['pos' => 'adv', 'advtype' => 'adadj'],
            'ADV'   => ['pos' => 'adv'],
            'ART'   => ['pos' => 'adj', 'prontype' => 'art'],
            'C'     => ['pos' => 'conj'],
            'INTJ'  => ['pos' => 'int'],
            'N'     => ['pos' => 'noun'],
            'NUM'   => ['pos' => 'num'],
            # adposition (pre- or postposition): jälkeen, ennen
            'PP'    => ['pos' => 'adp'],
            # foreign preposition: de
            'PREP'  => ['pos' => 'adp', 'adpostype' => 'prep'],
            # postposition: vieressä
            'PSP'   => ['pos' => 'adp', 'adpostype' => 'post'],
            # pronoun: sinä
            'PRON'  => ['pos' => 'noun'], # We need non-empty prontype but it should be added by another feature/atom.
            'V'     => ['pos' => 'verb'],
            'PUNCT' => ['pos' => 'punc'],
            # word form not found in lexicon: kiptšakkilais-oguusilaiseksi
            'NON-TWOL' => []
        },
        'encode_map' =>
        {
            'pos' => { 'noun' => { 'prontype' => { ''  => 'N',
                                                   '@' => 'PRON' }},
                       'adj'  => { 'prontype' => { 'art' => 'ART',
                                                   '@'   => 'A' }},
                       'num'  => 'NUM',
                       'verb' => 'V',
                       'adv'  => { 'advtype' => { 'adadj' => 'AD-A',
                                                  '@'     => 'ADV' }},
                       'adp'  => { 'adpostype' => { 'prep' => 'PREP',
                                                    'post' => 'PSP',
                                                    '@'    => 'PP' }},
                       'conj' => 'C',
                       'int'  => 'INTJ',
                       'punc' => 'PUNCT',
                       '@'    => { 'abbr' => { 'abbr' => '', # ABBR will be added by another atom.
                                               '@'    => { 'foreign' => { 'foreign' => '', # FORGN will be added by another atom.
                                                                          # Participles (PCP1) sometimes occur without explicit indication whether they should be considered verbs or adjectives.
                                                                          # Examples: jatkuvalla = continuous (jatkua = continue); käyttävällä = using (käyttää = use)
                                                                          '@'       => { 'verbform' => { 'part' => '',
                                                                                                         '@'    => 'NON-TWOL' }}}}}}}
        }
    );
    # ABBREVIATION ####################
    # abbreviation (eaa., ns., ven.)
    # This feature can appear as the only part of speech of the word, or it can join
    # the part of speech of the original word that has been abbreviated ("ADV|ABBR").
    $atoms{abbr} = $self->create_simple_atom
    (
        'intfeature' => 'abbr',
        'simple_decode_map' =>
        {
            'ABBR' => 'abbr'
        }
    );
    # FOREIGN WORD ####################
    # foreign word (British)
    $atoms{foreign} = $self->create_simple_atom
    (
        'intfeature' => 'foreign',
        'simple_decode_map' =>
        {
            'FORGN' => 'foreign'
        }
    );
    # PROPER NAME ####################
    # proper noun (Mikko)
    $atoms{prop} = $self->create_simple_atom
    (
        'intfeature' => 'nountype',
        'simple_decode_map' =>
        {
            'PROP' => 'prop'
        }
    );
    # PRONOUN TYPE ####################
    # Pronoun types: PERS DEM REL Q REFL/Q
    # Of these, only 'Q' appears in the documentation:
    # Q = quantifier (moni = many, much)
    $atoms{prontype} = $self->create_atom
    (
        'surfeature' => 'prontype',
        'decode_map' =>
        {
            # Q = quantifier (moni = many, much)
            # In the data, it occurs always together with PRON, i.e. 'Q|PRON'. Examples (translation by Google):
            # missään (anywhere), samalla (at the same time), toisen (next), kaikkia (all), jokaista (every), ainoa (only), samaan (same), molemmat (both)
            # Quantifier can also occur with one of the possessive suffixes.
            # It happens solely with the lemma "toinen" = "other" and the result translates as "each other" (lit. "my other", "your other", ...)
            'Q' => ['prontype' => 'ind'],
            # REFL/Q = reflexive quantifying pronoun (itseään = sám = self)
            'REFL/Q' => ['prontype' => 'ind', 'reflex' => 'reflex'],
            # PERS = personal pronoun (meidät = us)
            # minä = I, sinä = you, hän = he/she, me = we, te = you, he = they
            'PERS' => ['prontype' => 'prs'],
            # DEM = demonstrative pronoun (se = that, tuolla = there)
            'DEM' => ['prontype' => 'dem'],
            # REL = relative pronoun (mihin = where, mitä = what, joka = which)
            'REL' => ['prontype' => 'rel'],
            # There are two different features in the tagset that both say that a word is interrogative: INTG and INTERR.
            # INTG: only five tags observed, all PRON: lemmas "mikä" (what), "kuka" (who), "ken" (who). Other forms have REL instead of INTG.
            # INTERR: twelve tags observed with adjectives ("millainen" = "what") and adverbs ("miten" = "how").
            # interrogative pronoun (kuka = who, mikä = what)
            'INTG' => ['prontype' => 'int'],
            # interrogative adverb or adjective (kuinka = how, millainen = which, milloin = when, miksei = why not)
            # The word "miksei" (why not) is tagged at the same time as adverb and verb!
            # I am removing its tag from the list (otherwise it will be considered verb because V occurs later).
            'INTERR' => ['prontype' => 'int']
        },
        'encode_map' =>
        {
            'prontype' => { 'prs' => 'PERS',
                            'dem' => 'DEM',
                            'ind' => { 'reflex' => { 'reflex' => 'REFL/Q',
                                                     '@'      => 'Q' }},
                            'int' => { 'pos' => { 'adv' => 'INTERR',
                                                  'adj' => 'INTERR',
                                                  '@'   => 'INTG' }},
                            'rel' => 'REL' }
        }
    );
    # NUMERAL TYPE ####################
    # We can combine numeral type and form in one atom because they do not occur together.
    $atoms{numtype} = $self->create_atom
    (
        'surfeature' => 'numtype',
        'decode_map' =>
        {
            # ordinal numeral (ensimmäinen = first, toinen = second, kolmas = third)
            'ORD' => ['numtype' => 'ord'],
            # number expressed using Arabic digits
            # it also occurs with compound adjectives and nouns that contain digits (7., 9., 1.3-litrainen, 1980-luvun)
            'digit' => ['numform' => 'digit'],
            # number expressed using Roman numerals
            # (I, D, II, III, V, I:lle, M:lle, X-ryhmä)
            'roman' => ['numform' => 'roman']
        },
        'encode_map' =>
        {
            'numtype' => { 'ord' => 'ORD',
                           '@'   => { 'numform' => { 'digit' => 'digit',
                                                     'roman' => 'roman' }}}
        }
    );
    # COPULA ####################
    # Copula verb: COP (olla = to be)
    $atoms{copula} = $self->create_simple_atom
    (
        'intfeature' => 'verbtype',
        'simple_decode_map' =>
        {
            'COP' => 'cop'
        }
    );
    # ADVERB TYPE ####################
    # MAN
    $atoms{advtype} = $self->create_atom
    (
        'surfeature' => 'advtype',
        'decode_map' =>
        {
            # manner adverb (rohkeasti = boldly, hitaasti = slowly, henkisesti = mentally)
            'MAN'    => ['advtype' => 'man'],
        },
        'encode_map' =>
        {
            'advtype' => { 'man' => 'MAN' }
        }
    );
    # CONJUNCTION TYPE ####################
    # COORD SUB
    $atoms{conjtype} = $self->create_simple_atom
    (
        'intfeature' => 'conjtype',
        'simple_decode_map' =>
        {
            # coordinating conjunction (ja, että, vai, sekä, mutta)
            'COORD' => 'coor',
            # subordinating conjunction (kun, vaikka, ettei, jos, koska)
            'SUB'   => 'sub',
            # comparating conjunction (kuin = as)
            'CMPR'  => 'comp'
        }
    );
    # PUNCTUATION TYPE ####################
    # DASH|PUNCT, PUNCT|QUOTE, PUNCT|ENDASH...
    $atoms{punctype} = $self->create_atom
    (
        'surfeature' => 'punctype',
        'decode_map' =>
        {
            'DASH'   => ['punctype' => 'dash'],
            'ENDASH' => ['punctype' => 'dash', 'other' => {'dashtype' => 'en'}],
            'EMDASH' => ['punctype' => 'dash', 'other' => {'dashtype' => 'em'}],
            'QUOTE'  => ['punctype' => 'quot']
        },
        'encode_map' =>
        {
            'punctype' => { 'dash' => { 'other/dashtype' => { 'en' => 'ENDASH',
                                                              'em' => 'EMDASH',
                                                              '@'  => 'DASH' }},
                            'quot' => 'QUOTE' }
        }
    );
    # DEGREE OF COMPARISON ####################
    $atoms{degree} = $self->create_simple_atom
    (
        'intfeature' => 'degree',
        'simple_decode_map' =>
        {
            # positive (kuuma, hyvä)
            'POS' => 'pos',
            # comparative (kuumempi, parempi)
            'CMP' => 'comp',
            # superlative (kuumin, paras)
            'SUP' => 'sup'
        }
    );
    # CASE ####################
    $atoms{case} = $self->create_simple_atom
    (
        'intfeature' => 'case',
        'simple_decode_map' =>
        {
            # nominative (koira = dog)
            'NOM' => 'nom',
            # genitive (koiran)
            'GEN' => 'gen',
            # partitive (koiraa)
            'PTV' => 'par',
            # essive (koirana)
            'ESS' => 'ess',
            # translative (koiraksi)
            'TRA' => 'tra',
            # inessive (koirassa)
            'INE' => 'ine',
            # elative (koirasta)
            'ELA' => 'ela',
            # illative (koiraan)
            'ILL' => 'ill',
            # adessive (koiralla)
            'ADE' => 'ade',
            # ablative (koiralta)
            'ABL' => 'abl',
            # allative (koiralle)
            'ALL' => 'all',
            # abessive (koiratta)
            'ABE' => 'abe',
            # comitative (koirineen)
            'CMT' => 'com',
            # instructive (koirin)
            'INS' => 'ins',
            # accusative: only with a few pronouns (meidät = us, sinut = thee, hänet = him, minut = me, heidät = them)
            'ACC' => 'acc'
        }
    );
    # NUMBER ####################
    $atoms{number} = $self->create_simple_atom
    (
        'intfeature' => 'number',
        'simple_decode_map' =>
        {
            # singular (kala = fish)
            'SG' => 'sing',
            # plural (kalat)
            'PL' => 'plur'
        }
    );
    # POSSESSIVE SUFFIX ####################
    $atoms{poss} = $self->create_atom
    (
        'surfeature' => 'poss',
        'decode_map' =>
        {
            # 1st person singular (my) (tyttäreni = my daughter)
            '1SG' => ['poss' => 'poss', 'possperson' => '1', 'possnumber' => 'sing'],
            # 2nd person singular (your) (tyttäresi)
            '2SG' => ['poss' => 'poss', 'possperson' => '2', 'possnumber' => 'sing'],
            # 3rd person singular or plural (his, her, its, their) (tyttärensä)
            '3'   => ['poss' => 'poss', 'possperson' => '3'],
            # 1st person plural (our) (tyttäremme)
            '1PL' => ['poss' => 'poss', 'possperson' => '1', 'possnumber' => 'plur'],
            # 2nd person plural (your) (tyttärenne)
            '2PL' => ['poss' => 'poss', 'possperson' => '2', 'possnumber' => 'plur']
        },
        'encode_map' =>
        {
            'possperson' => { '1' => { 'possnumber' => { 'plur' => '1PL',
                                                         '@'    => '1SG' }},
                              '2' => { 'possnumber' => { 'plur' => '2PL',
                                                         '@'    => '2SG' }},
                              '3' => '3' }
        }
    );
    # MOOD ####################
    $atoms{mood} = $self->create_atom
    (
        'surfeature' => 'mood',
        'decode_map' =>
        {
            # There is no feature for indicative forms (lukee = reads, menee = goes).
            # imperative (lue, mene)
            'IMPV' => ['verbform' => 'fin', 'mood' => 'imp'],
            # conditional (lukisi, menisi)
            'COND' => ['verbform' => 'fin', 'mood' => 'cnd'],
            # potential (lukenee, mennee)
            'POTN' => ['verbform' => 'fin', 'mood' => 'pot']
        },
        'encode_map' =>
        {
            'mood' => { 'imp' => 'IMPV',
                        'cnd' => 'COND',
                        'pot' => 'POTN' }
        }
    );
    # TENSE ####################
    $atoms{tense} = $self->create_simple_atom
    (
        'intfeature' => 'tense',
        'simple_decode_map' =>
        {
            # present (haluan = I want to)
            'PRES' => 'pres',
            # past (halusin = I wanted to)
            'PAST' => 'past'
        }
    );
    # VOICE ####################
    $atoms{voice} = $self->create_simple_atom
    (
        'intfeature' => 'voice',
        'simple_decode_map' =>
        {
            # active (uin = I swim)
            'ACT' => 'act',
            # passive (uidaan)
            'PSS' => 'pass'
        }
    );
    # PERSON AND NUMBER OF THE SUBJECT OF THE VERB ####################
    $atoms{person} = $self->create_atom
    (
        'surfeature' => 'poss',
        'decode_map' =>
        {
            # Person: SG1 SG2 SG3 PL1 PL2 PL3 PE4
            # 1st person singular (menen = I go)
            'SG1' => ['number' => 'sing', 'person' => '1'],
            # 2nd person singular (menet = you go)
            'SG2' => ['number' => 'sing', 'person' => '2'],
            # 3rd person singular (menee = he goes)
            'SG3' => ['number' => 'sing', 'person' => '3'],
            # 1st person plural (menemme = we go)
            'PL1' => ['number' => 'plur', 'person' => '1'],
            # 2nd person plural (menette = you go)
            'PL2' => ['number' => 'plur', 'person' => '2'],
            # 3rd person plural (menevät = they go)
            'PL3' => ['number' => 'plur', 'person' => '3'],
            # passive ending (mennään)
            # In modern colloquial Finnish, the passive form of the verb is used instead of the active first person plural indicative and imperative.
            # We cannot set 'style' => 'coll' because the tagset includes means to mark colloquial language and it does not apply it here.
            # (Setting 'style' => 'coll' would mean that on encoding we would produce the 'st-cllq' feature that was not in the input tag.)
            'PE4' => ['number' => 'plur', 'person' => '1', 'variant' => '6']
        },
        'encode_map' =>
        {
            'number' => { 'sing' => { 'person' => { '1' => 'SG1',
                                                    '2' => 'SG2',
                                                    '3' => 'SG3' }},
                          'plur' => { 'person' => { '1' => { 'variant' => { '6' => 'PE4',
                                                                            '@' => 'PL1' }},
                                                    '2' => 'PL2',
                                                    '3' => 'PL3' }}}
        }
    );
    # NEGATIVENESS ####################
    $atoms{neg} = $self->create_atom
    (
        'surfeature' => 'neg',
        'decode_map' =>
        {
            # negative verb (en, et, ei)
            # Sometimes even verbs have NEG and not NEGV, so we must remember the distinction in the 'other' feature.
            'NEGV' => ['negativeness' => 'neg', 'other' => {'negativeness' => 'negv'}],
            # negative form (en tehnyt = I did not do)
            'NEG'  => ['negativeness' => 'neg', 'other' => {'negativeness' => 'neg'}]
        },
        'encode_map' =>
        {
            'other/negativeness' => { 'negv' => 'NEGV',
                                      'neg'  => 'NEG',
                                      '@'    => { # for some reason, copula verbs do not use NEGV but NEG
                                                  'negativeness' => { 'neg' => { 'pos' => { 'verb' => { 'verbtype' => { 'cop' => 'NEG',
                                                                                                                        '@'   => 'NEGV' }},
                                                                                            'conj' => 'NEGV',
                                                                                            '@'    => 'NEG' }}}}}
        }
    );
    # INFINITIVE ####################
    # There are several verb forms in Finnish that are called infinitives.
    # Infinitives: INF1 INF2 INF3 INF5
    # The 4th infinitive (tuleminen) is interpreted as a noun.
    $atoms{inf} = $self->create_atom
    (
        'surfeature' => 'inf',
        'decode_map' =>
        {
            # 1st infinitive (tulla, tullakseni = to become)
            'INF1' => ['verbform' => 'inf', 'variant' => '1'],
            # 2nd infinitive (tullessaan, tullessa)
            'INF2' => ['verbform' => 'inf', 'variant' => '2'],
            # 3rd infinitive (tulemaan)
            'INF3' => ['verbform' => 'ger'],
            # 5th infinitive (tulemaisillaan)
            'INF5' => ['verbform' => 'inf', 'variant' => '5']
        },
        'encode_map' =>
        {
            'verbform' => { 'inf' => { 'variant' => { '5' => 'INF5',
                                                      '2' => 'INF2',
                                                      '@' => 'INF1' }},
                            'ger' => 'INF3' }
        }
    );
    # PARTICIPLE ####################
    # Participles: PCP1 PCP2
    $atoms{pcp} = $self->create_atom
    (
        'surfeature' => 'pcp',
        'decode_map' =>
        {
            # 1st participle (lentävä = flying, lennettävä = flown)
            'PCP1' => ['verbform' => 'part', 'variant' => '1'],
            # 2nd participle (lentänyt = flown, lennetty = flown)
            'PCP2' => ['verbform' => 'part', 'variant' => '2']
        },
        'encode_map' =>
        {
            'verbform' => { 'part' => { 'variant' => { '2' => 'PCP2',
                                                       '@' => 'PCP1' }}}
        }
    );
    # CLITIC ####################
    # Clitics: hAn kA kAAn kin kO pA s
    $atoms{clitic} = $self->create_atom
    (
        'surfeature' => 'clitic',
        'decode_map' =>
        {
            # Appealing clitic -han/-hän (poikahan).
            # This clitic is to appeal to the listener:
            # Olethan kävellyt?
            # You have walked, right?
            'hAn'   => ['other' => {'clitic' => 'hAn'}],
            # Copulative clitic -ka/-kä (eikä).
            # This clitic is used in negative forms to work as copula:
            # en juokse enkä kävele
            # I don't run nor (do I) walk.
            'kA'    => ['other' => {'clitic' => 'kA'}],
            # -kaan/-kään (poikakaan)
            'kAAn'  => ['other' => {'clitic' => 'kAAn'}],
            # -kin (poikakin)
            'kin'   => ['other' => {'clitic' => 'kin'}],
            # -ko/-kö (oletko)
            'kO'    => ['other' => {'clitic' => 'kO'}],
            # -kohan/-köhän (miksiköhän = I wonder why, olisikohan = I wonder if)
            'kOhAn' => ['other' => {'clitic' => 'kOhAn'}],
            # -pa/-pä (oletpa)
            'pA'    => ['other' => {'clitic' => 'pA'}],
            # Emphatic (zdůrazňovací) clitic -s (onpas)
            's'     => ['other' => {'clitic' => 's'}]
        },
        'encode_map' =>
        {
            'other/clitic' => { 'hAn'   => 'hAn',
                                'kA'    => 'kA',
                                'kAAn'  => 'kAAn',
                                'kin'   => 'kin',
                                'kO'    => 'kO',
                                'kOhAn' => 'kOhAn',
                                'pA'    => 'pA',
                                's'     => 's' }
        }
    );
    # STYLE ####################
    # Style: st-arch st-cllq st-derog st-slang st-vrnc st-hi
    # archaic colloquial derogative slang vernacular hi?
    # zastaralý hovorový hanlivý slang nářečí knižní?
    $atoms{style} = $self->create_simple_atom
    (
        'intfeature' => 'style',
        'simple_decode_map' =>
        {
            'st-arch'  => 'arch',
            'st-cllq'  => 'coll',
            'st-derog' => 'derg',
            'st-slang' => 'slng',
            'st-vrnc'  => 'vrnc',
            'st-hi'    => 'form'
        }
    );
    # UPPERCASE ####################
    # up: is the first letter of the word form uppercase?
    # We can decode and recover this information but we will not show it in our list of known tags.
    $atoms{up} = $self->create_atom
    (
        'surfeature' => 'up',
        'decode_map' =>
        {
            'up' => ['other' => {'uppercase' => 'yes'}]
        },
        'encode_map' =>
        {
            'other/uppercase' => { 'yes' => 'up' }
        }
    );
    # TRUNCATED COMPOUND ####################
    # TrunCo seems to mark hyphenated prefixes occurring separately.
    $atoms{trunco} = $self->create_simple_atom
    (
        'intfeature' => 'hyph',
        'simple_decode_map' =>
        {
            'TrunCo' => 'hyph'
        }
    );
    # UNKNOWN FEATURES ####################
    # LAT REF TEMP
    $atoms{unknown} = $self->create_atom
    (
        'surfeature' => 'unknown',
        'decode_map' =>
        {
            # LAT ???
            # Typically occurs with the first infinitive (LAT|INF1|V).
            # It never occurs without INF1 and I found only three INF1 tags without LAT (all three were in the translative case).
            'LAT' => ['other' => {'lat' => 'yes'}],
            # REF ???
            # A very rare feature of verbs. Reflexivity?
            # PAST|PSS|REF|V: julkaistun = published, mietityn = thought about, tuomitun = convicted
            # "tuomitun" is homonymous with the second participle in genitive (in nominative, it is "tuomittu")
            # same with "julkaistun" (nominative participle "julkaistu") but not with "mietityn"
            # PSS|REF|PRES|V: tultavan (tulla = become), kuvattavan (kuvata = shoot), hoidettavan (hoitaa = manage)
            # similar to the first participle: tultava
            'REF' => ['other' => {'ref' => 'yes'}],
            # TEMP ???
            # Rare feature of PAST|ACT verbs ending in -tua, -tyä, -tuaan.
            # Maybe it expresses "after doing the action of the verb"?
            # tultua = after the entry (tulla = become); iskettyä = struck (iskeä = strike); kirjattua = recognized (kirjata = record)
            'TEMP' => ['other' => {'temp' => 'yes'}],
        },
        'encode_map' =>
        {
            'other/lat' => { 'yes' => 'LAT',
                             '@'   => { 'other/ref' => { 'yes' => 'REF',
                                                         '@'   => { 'other/temp' => { 'yes' => 'TEMP' }}}}}
        }
    );
    # *null* node inserted instead of ellided token; it is always tagged as a special case of verb (the tag is "V|NULL").
    # S mysteriously occurs with a few foreign words (child, monkey, death); tags "S|FORGN" and "S|FORGN|up".
    # The 't-EUparl' "feature" is probably a bug in data preparation / tagging.
    # It occurs only once, with the word 'europarlamenttivaaleissa' (= EU Parliament polls).
    # There are several other similar.
    # if($feature =~ m/^t-(EUparl|MSilocat|MSasiakirja|EU-vk|MSolocat|MSlukumäärä)$/)
    # -pi ####################
    # -pi (ompi = finer, nicer) ???
    # Not found in the corpus.
    # Other features occur in data although they are not documented.
    # MERGED ATOM TO DECODE ANY FEATURE VALUE ####################
    my @fatoms = map {$atoms{$_}} @{$self->features_all()};
    $atoms{feature} = $self->create_merged_atom
    (
        'surfeature' => 'feature',
        'atoms'      => \@fatoms
    );
    return \%atoms;
}



#------------------------------------------------------------------------------
# Various DV-, DN- and DA- features mark morphemes that derive new word and
# change the part of speech. Several DX- features can occur in one tag, e.g.
# 1PL|DV-ILE|ELA|N|DV-U|SG or DA-UUS|3|N|DN-LLINEN|PTV|SG.
#
# If the tag contains one or more features describing derivational processes,
# this method will group those features into one. This way we get something
# that can be handled as one feature and stored in the 'other' feature of
# Interset.
#
# The following derivation features occur in the data:
#
# Deverbatives. The resulting part of speech marked in a separate feature and
# it can be noun, adjective or adverb.
#
# DV-NEISUUS 5
# All examples of DV-NEISUUS are nouns and are tagged N.
# eristyneisyys = isolation (eriste = insulation); kuolleisuus = mortality; oppineisuus = erudition (oppia = learn)
#
# DV-NTI 49
# All examples of DV-NTI are nouns and are tagged N.
# myynti = sale (myydä = to sell); luettelointi = listing (luetteloida = to list); ulosvienti = going out (viedä = to export)
#
# DV-NA 2
# All examples of DV-NA are nouns and are tagged N.
# kutina = itch; kahina = rustling
#
# DV-VAINEN 38
# Examples of DV-VAINEN are tagged as A, ADV or N.
# adjective: tyytyväinen = pleased; luottavainen = trusting
# adverb: päättäväisemmin = decisively (päättäväinen = resolute)
# The noun examples also contain DA-UUS that derives nouns from adjectives.
# DA-UUS appears earlier in the feature sequence but it was applied later in the word formation process.
# noun (DA-UUS|NOM|SG|DV-VAINEN|N): tulevaisuus = future (tulla = come, become; tulevainen = coming; tulevaisuus = that what is coming)
#
# DV-MATON 51
# DV-JA 594
# DV-SKELE 5
# DV-MINEN 382
# DV-MA 142
# DV-UTTA 1
# DV-NTAA 40
# DV-NTA 98
# DV-ELE 176
# DV-TTA 259
# DV-US 643
# DV-U 505
# DV-ILE 63
# DV-UTU 46
#
# Denominatives. The resulting part of speech is marked in a separate feature
# and usually it is A or ADV. (It can be noun if there are two derivations,
# e.g. aktiivisuus has DN-INEN (created aktiivinen = active) and DA-UUS
# (created aktiivisuus = activity).
# DN-INEN 44, DN-ITTAIN 34, DN-LAINEN 168, DN-LLINEN 329, DN-MAINEN 17,
# DN-TAR 1, DN-TON 40
#
# Deadjectives. The resulting part of speech is noun and they are tagged "N".
# DA-US 101 ... sairaus = illness, rakkaus = love
# DA-UUS 280 ... varmuus = affirmation, tyhjyys = emptiness
#------------------------------------------------------------------------------
sub decode_derivation
{
    my $self = shift;
    my $tag = shift;
    my @features = split(/\|/, $tag);
    my @features1 = grep {!m/^D[VNA]-/} @features;
    my $tag1 = join('|', @features1);
    my @dev = grep {m/^D[VNA]-/} @features;
    my $derivation = join('+', @dev);
    return ($tag1, $derivation);
}



#------------------------------------------------------------------------------
# Decodes a physical tag (string) and returns the corresponding feature
# structure.
#------------------------------------------------------------------------------
sub decode
{
    my $self = shift;
    my $tag = shift;
    my $fs = Lingua::Interset::FeatureStructure->new();
    $fs->set_tagset('fi::turku');
    my $atoms = $self->atoms();
    # Tag is a sequence of features separated by vertical bars.
    # There are just the feature values, not attribute-value pairs.
    # example: n/com,sg,nom ###!!! replace the Estonian example by a Finnish one
    # Some words are tagged as conjunctions and verbs at the same time:
    # muttei = but not (C|NEGV|SG3|COORD|V)
    # ettei = that there is no (ettemme C|NEGV|SUB|PL1|V)
    # eivätkä = and not (C|PL3|NEGV|kA|COORD|V)
    # ellei = unless (C|SUB|SG3|NEGV|V)
    # The first (left) part-of-speech feature should be preferred.
    # Features are probably ordered as new affixes are identified and removed during analysis.
    # The rightmost feature ("V") applies to the stem in the lexicon, while the leftmost feature ("C") identifies the resulting part of speech.
    # We will remove the "V" from the tags returned by list() so that tests can be passed.
    # However, we will decode the tag correctly. We will not preserve the "V" when encoding.
    $tag =~ s/^(C\|.*)\|V$/$1/;
    # Separate the derivational features. There may be more than one.
    my $derivation;
    ($tag, $derivation) = $self->decode_derivation($tag);
    my @features = split(/\|/, $tag);
    foreach my $feature (@features)
    {
        $atoms->{feature}->decode_and_merge_hard($feature, $fs);
    }
    # Add the derivational information to the other feature.
    if(defined($derivation) && $derivation ne '')
    {
        my $other = $fs->other();
        my %hash;
        if(ref($other) ne 'HASH')
        {
            $other = \%hash;
        }
        $other->{'derivation'} = $derivation;
        $fs->set('other', $other);
    }
    return $fs;
}



#------------------------------------------------------------------------------
# Takes feature structure and returns the corresponding physical tag (string).
#------------------------------------------------------------------------------
sub encode
{
    my $self = shift;
    my $fs = shift; # Lingua::Interset::FeatureStructure
    my @feature_names = @{$self->features_all()};
    my $atoms = $self->atoms();
    my @features = ();
    # Verbs use the SG1 ... PL3 features and they do not use the SG / PL features.
    my $number_with_person = $fs->person() ne '';
    foreach my $feature (@feature_names)
    {
        next if($number_with_person && $feature eq 'number');
        my $value = $atoms->{$feature}->encode($fs);
        push(@features, $value) unless($value eq '');
    }
    # If there is information on derivational morphology, add it to the features.
    my $derivation = $fs->get_other_subfeature('fi::turku', 'derivation');
    my @derivation = split(/\+/, $derivation);
    if(@derivation)
    {
        push(@features, @derivation);
    }
    my $tag = join('|', @features);
    return $tag;
}



#------------------------------------------------------------------------------
# Returns reference to list of known tags.
# Tags were collected from the corpus.
# 598 tags have been observed in the corpus.
# We removed some tags due to inconsistency between pos and features (e.g.
# conj-c/sub).
# Removed features:
# .cap, %cap ... the word starts with an uppercase letter
# 252 tags survived.
# Then we added missing combinations of number+case (except for the additive
# case, whose usage is limited) for nominals and person+number for verbs.
# 614 total tags after the extension.
#------------------------------------------------------------------------------
sub list
{
    my $self = shift;
    my $list = <<end_of_list
1PL|DV-ILE|ELA|N|DV-U|SG
1SG|ADE|SG|N
1SG|ALL|SG|N
1SG|DA-UUS|NOM|SG|N
1SG|DV-TTA|N|ADE|DV-ELE|SG
1SG|DV-US|ADE|SG|N
1SG|ELA|SG|N
1SG|ELA|SG|up|N
1SG|GEN|PL|N
1SG|ILL|SG|DV-JA|N
1SG|ILL|SG|N
1SG|INE|SG|N
1SG|NOM|DV-US|SG|N
1SG|NOM|SG|N
1SG|NOM|SG|kin|N
1SG|NOM|up|SG|N
1SG|PRON|ALL|REFL/Q|SG
1SG|PRON|REFL/Q|SG|NOM
1SG|PRON|REFL/Q|SG|PTV
1SG|PSP|ABL
1SG|PTV|SG|N
1SG|SG|GEN|N
1SG|st-cllq|ELA|SG|N
1SG|st-cllq|ILL|SG|N
1SG|st-cllq|NOM|SG|N
3|ABL|PL|N
3|ADE|PL|N
3|ADE|SG|N
3|ADE|up|PL|N
3|CMT|DV-JA|N
3|CMT|DV-NTI|N
3|CMT|N
3|ELA|PL|N
3|ELA|SG|DV-JA|N
3|ELA|SG|N
3|ESS|DV-JA|PL|N
3|ESS|PL|N
3|GEN|PL|N
3|N|SG|GEN|DA-US
3|SG|GEN|N
3|up|ESS|PL|N
A
ABBR
ABL|PL|N
ABL|SG|DV-MINEN|N
ABL|SG|DV-NTA|1PL|N
ACT|COND|PL1|DV-TTA|V
ACT|COND|PL1|V
ACT|DV-ELE|INF2|INS|V
ACT|DV-ELE|PL3|PRES|V
ACT|DV-UTU|PL3|PRES|V
ACT|IMPV|PL1|V
ACT|IMPV|SG2|V
ACT|IMPV|up|SG2|V
ACT|INF2|INS|V
ACT|PL1|PRES|V
ACT|PL2|PRES|V
ACT|PL3|PRES|DV-TTA|V
ACT|PL3|PRES|V
ACT|PL3|up|PRES|V
ACT|SG3|DV-ELE|COND|V
ACT|SG3|DV-ELE|PRES|V
ACT|SG3|DV-UTU|PRES|V
ACT|SG3|V|PRES|DV-ILE
ACT|V|INF2|INS|DV-ILE
AD-A
AD-A|kin
ADE|DV-ELE|INF3|DV-TTA|V
ADE|DV-ELE|INF3|V
ADE|DV-JA|PL|N
ADE|INF3|DV-TTA|V
ADE|INF3|V
ADE|INF3|up|V
ADE|NUM|SG
ADE|N|SG|DA-US
ADE|N|SG|up|PROP
ADE|N|up|PL|PROP
ADE|PL|N
ADE|SG|1PL|N
ADE|SG|ABBR
ADE|SG|DV-JA|DV-TTA|N
ADE|SG|DV-JA|N
ADE|SG|N
ADE|SG|POS|PCP1|ACT
ADE|SG|kin|N
ADE|SG|up|N
ADE|up|PL|N
ADV
ADV|3
ADV|3|ADE
ADV|3|ADE|up
ADV|ABBR
ADV|ABL
ADV|ADE
ADV|ADE|CMP
ADV|ADE|kin
ADV|ADE|up
ADV|ALL
ADV|ALL|3
ADV|ALL|kin
ADV|ALL|up
ADV|DN-INEN|POS|MAN
ADV|DN-ITTAIN
ADV|DN-ITTAIN|DV-JA
ADV|DN-ITTAIN|up
ADV|DN-LLINEN|POS|MAN
ADV|DN-LLINEN|up|POS|MAN
ADV|DN-MAINEN|POS|MAN
ADV|DV-MATON|POS|MAN
ADV|DV-US|MAN|DN-LLINEN|POS
ADV|ELA
ADV|ESS|CMP
ADV|ESS|kin|CMP
ADV|ILL
ADV|ILL|3
ADV|ILL|kin
ADV|ILL|up
ADV|INE
ADV|INE|3
ADV|INE|up
ADV|INTERR
ADV|MAN
ADV|MAN|CMP
ADV|MAN|DV-VAINEN|CMP
ADV|MAN|POS|PCP1|ACT
ADV|MAN|SUP
ADV|MAN|up|SUP
ADV|PCP2|POS|ACT|DV-U|MAN
ADV|POS|MAN
ADV|POS|MAN|PCP2|ACT
ADV|PSS|MAN|PCP2|POS
ADV|PSS|POS|PCP1|MAN
ADV|PTV|CMP
ADV|REL
ADV|hAn
ADV|kAAn
ADV|kAAn|ADE
ADV|kin
ADV|pA
ADV|pA|up
ADV|st-cllq|ALL
ADV|st-cllq|POS|MAN
ADV|up
ADV|up|ABBR
ADV|up|ABL
ADV|up|INTERR
ADV|up|MAN
ADV|up|POS|MAN
ADV|up|POS|PCP1|PSS|MAN
ADV|up|hAn
ADV|up|kin
ALL|1SG|PL|N
ALL|3|DV-JA|PL|N
ALL|3|PL|N
ALL|DV-ELE|DV-JA|PL|N
ALL|DV-JA|PL|N
ALL|DV-NTA|PL|N
ALL|NUM|SG
ALL|N|SG|DA-US
ALL|N|SG|up|PROP
ALL|N|up|PL|PROP
ALL|PL|DV-JA|DV-TTA|N
ALL|PL|N
ALL|PL|POS|PCP1|ACT
ALL|POS|PCP1|ACT|DV-U|PL
ALL|POS|PCP2|ACT|DV-ELE|SG
ALL|POS|PCP2|ACT|DV-U|PL
ALL|SG|3|N
ALL|SG|DV-JA|N
ALL|SG|N
ALL|SG|POS|PCP1|ACT
ALL|SG|kin|N
ALL|up|3|PL|N
ALL|up|DV-JA|PL|N
ALL|up|PL|N
ALL|up|SG|ABBR
ALL|up|SG|N
ALL|up|SG|kin|N
A|2SG|SG|POS|GEN
A|3|ADE|PL|SUP
A|3|ADE|POS|PL
A|3|ADE|SG|POS
A|ABL|POS|DN-LAINEN|PROP|PL
A|ABL|POS|DN-LAINEN|PROP|SG
A|ABL|POS|PL
A|ABL|SG|DN-INEN|POS
A|ABL|SG|DV-MATON|POS
A|ACT|PCP1|SUP|PTV|PL
A|ACT|PCP2|SUP|PTV|PL
A|ADE|DN-INEN|POS|PL
A|ADE|PL|CMP
A|ADE|POS|PL
A|ADE|SG|CMP
A|ADE|SG|POS
A|ADE|SG|SUP
A|ADE|SG|kin|CMP
A|ADE|SG|up|CMP
A|ALL|DV-MATON|POS|PL
A|ALL|PL|CMP
A|ALL|PL|SUP
A|ALL|POS|DN-LAINEN|PROP|PL
A|ALL|POS|DN-LAINEN|PROP|SG
A|ALL|POS|PL
A|ALL|SG|CMP
A|ALL|SG|POS
A|ALL|up|SG|CMP
A|ALL|up|SG|POS
A|CMT|POS
A|COP|ELA|PCP2|POS|ACT|PL
A|COP|PCP2|POS|ACT|GEN|PL
A|COP|PCP2|POS|ACT|PTV|PL
A|DN-INEN|POS|PL|GEN
A|DN-LLINEN|ADE|SG|POS
A|DN-LLINEN|ALL|POS|PL
A|DN-LLINEN|ALL|SG|POS
A|DN-LLINEN|ELA|PL|SUP
A|DN-LLINEN|ELA|POS|PL
A|DN-LLINEN|ELA|SG|POS
A|DN-LLINEN|ESS|POS|PL
A|DN-LLINEN|POS|ILL|PL
A|DN-LLINEN|POS|PL|GEN
A|DN-LLINEN|SG|ILL|CMP
A|DN-LLINEN|SG|POS|GEN
A|DN-LLINEN|SG|POS|ILL
A|DV-MATON|POS|DV-U|INE|PL
A|DV-MATON|POS|DV-U|SG|GEN
A|DV-MATON|POS|PL|GEN
A|DV-NTA|POS|DN-LLINEN|GEN|PL
A|DV-US|POS|DN-LLINEN|PTV|PL
A|DV-US|POS|DN-LLINEN|SG|GEN
A|DV-US|POS|DV-TTA|DN-LLINEN|PTV|PL
A|ELA|DN-MAINEN|POS|PL
A|ELA|DV-MATON|POS|PL
A|ELA|PCP1|ACT|SUP|PL
A|ELA|PCP2|SUP|PSS|PL
A|ELA|PCP2|SUP|PSS|SG
A|ELA|PL|CMP
A|ELA|PL|SUP
A|ELA|POS|DN-LAINEN|PROP|PL
A|ELA|POS|DN-LAINEN|PROP|SG
A|ELA|POS|PL
A|ELA|SG|CMP
A|ELA|SG|POS
A|ELA|SG|POS|INTERR
A|ELA|SG|SUP
A|ELA|SG|kin|SUP
A|ELA|up|PL|CMP
A|ESS|DV-VAINEN|PL|POS
A|ESS|PCP2|SUP|PSS|SG
A|ESS|POS|DN-LAINEN|PROP|SG
A|ESS|POS|PL
A|ESS|POS|PL|kin
A|ESS|SG|DV-MATON|POS
A|FORGN
A|FORGN|up
A|GEN|PL|CMP
A|GEN|PL|SUP
A|ILL|DV-MATON|POS|PL
A|ILL|PCP2|SUP|PSS|PL
A|ILL|PL|CMP
A|ILL|PL|SUP
A|ILL|POS|DN-LAINEN|PROP|PL
A|ILL|POS|DN-LAINEN|PROP|SG
A|ILL|POS|PL
A|ILL|SG|CMP
A|ILL|SG|POS
A|ILL|SG|POS|kin
A|ILL|up|POS|PL
A|ILL|up|SG|CMP
A|ILL|up|SG|POS
A|INE|DN-LLINEN|POS|PL
A|INE|DN-LLINEN|SG|POS
A|INE|DN-MAINEN|POS|PL
A|INE|DV-VAINEN|PL|POS
A|INE|PL|CMP
A|INE|POS|PL
A|INE|SG|CMP
A|INE|SG|DN-INEN|POS
A|INE|SG|DV-MATON|POS
A|INE|SG|POS
A|INE|SG|POS|kin
A|INE|SG|SUP
A|INE|up|POS|PL
A|INE|up|SG|POS
A|INS|PL|CMP
A|NOM|1SG|POS|PL
A|NOM|3|SG|POS
A|NOM|3|SG|SUP
A|NOM|ACT|PCP1|SUP|PL
A|NOM|ACT|PCP1|SUP|SG
A|NOM|ACT|PCP2|SUP|SG
A|NOM|DN-INEN|POS|PL
A|NOM|DN-LLINEN|POS|PL
A|NOM|DN-LLINEN|SG|POS
A|NOM|DN-LLINEN|SG|SUP
A|NOM|DV-MATON|POS|PL
A|NOM|DV-US|POS|DN-LLINEN|SG
A|NOM|PCP1|ACT|SG|CMP
A|NOM|PCP1|SUP|PSS|SG
A|NOM|PCP2|ACT|PL|CMP
A|NOM|PCP2|SUP|PSS|DV-ELE|SG
A|NOM|PCP2|SUP|PSS|SG
A|NOM|PL|CMP
A|NOM|PL|SUP
A|NOM|POS|DN-LAINEN|PROP|PL
A|NOM|POS|DN-LAINEN|PROP|SG
A|NOM|POS|DN-LLINEN|kin|SG
A|NOM|POS|PL
A|NOM|SG|CMP
A|NOM|SG|DN-INEN|POS
A|NOM|SG|DN-INEN|SUP
A|NOM|SG|DN-MAINEN|POS
A|NOM|SG|DV-MATON|POS
A|NOM|SG|DV-VAINEN|POS
A|NOM|SG|POS
A|NOM|SG|POS|1PL
A|NOM|SG|POS|INTERR
A|NOM|SG|POS|TrunCo
A|NOM|SG|POS|kin
A|NOM|SG|SUP
A|NOM|SG|kAAn|SUP
A|NOM|kin|PL|CMP
A|NOM|up|1SG|POS|SG
A|NOM|up|ACT|PCP1|SUP|SG
A|NOM|up|ACT|PCP2|SUP|SG
A|NOM|up|DN-INEN|POS|SG
A|NOM|up|PCP2|SUP|PSS|SG
A|NOM|up|PL|CMP
A|NOM|up|PL|SUP
A|NOM|up|POS|DN-INEN|PL
A|NOM|up|POS|DN-LAINEN|PROP|PL
A|NOM|up|POS|DN-LAINEN|PROP|SG
A|NOM|up|POS|DN-LLINEN|PL
A|NOM|up|POS|DN-LLINEN|SG
A|NOM|up|POS|INTERR|SG
A|NOM|up|POS|PL
A|NOM|up|SG|CMP
A|NOM|up|SG|POS
A|NOM|up|SG|SUP
A|NOM|up|kO|POS|PL
A|NOM|up|st-cllq|POS|SG
A|PCP1|ACT|PTV|SG|CMP
A|PCP1|PTV|PSS|PL|CMP
A|PCP2|SUP|PSS|SG|GEN
A|PL|POS|INTERR|GEN
A|POS|DN-LAINEN|ADE|PROP|SG
A|POS|DN-LAINEN|INE|PROP|PL
A|POS|DN-LAINEN|INE|PROP|SG
A|POS|DN-LAINEN|PROP|GEN|PL
A|POS|DN-LAINEN|PROP|SG|GEN
A|POS|DN-LAINEN|PTV|PROP|PL
A|POS|DN-LAINEN|PTV|PROP|SG
A|POS|DN-LLINEN|kin|PTV|SG
A|POS|PL|GEN
A|POS|PL|INS
A|PTV|1SG|POS|PL
A|PTV|3|POS|PL
A|PTV|3|SG|POS
A|PTV|DN-INEN|POS|PL
A|PTV|DN-LLINEN|POS|PL
A|PTV|DN-LLINEN|SG|CMP
A|PTV|DN-LLINEN|SG|POS
A|PTV|DV-MATON|POS|PL
A|PTV|DV-UTU|POS|PL
A|PTV|DV-VAINEN|PL|POS
A|PTV|PL|CMP
A|PTV|PL|SUP
A|PTV|POS|INTERR|PL
A|PTV|POS|PL
A|PTV|SG|CMP
A|PTV|SG|DN-INEN|POS
A|PTV|SG|DN-MAINEN|POS
A|PTV|SG|DV-MATON|POS
A|PTV|SG|DV-MATON|SUP
A|PTV|SG|POS
A|PTV|SG|POS|DV-TTA
A|PTV|SG|POS|INTERR
A|PTV|SG|POS|TrunCo
A|PTV|SG|POS|kin
A|PTV|SG|SUP
A|PTV|SG|kin|CMP
A|PTV|up|PL|SUP
A|PTV|up|POS|PL
A|PTV|up|SG|POS
A|PTV|up|SG|SUP
A|SG|ABL|CMP
A|SG|ABL|POS
A|SG|ABL|SUP
A|SG|ADE|DN-INEN|POS
A|SG|ALL|DN-INEN|POS
A|SG|DN-INEN|POS|GEN
A|SG|DN-LLINEN|ABL|POS
A|SG|DN-LLINEN|ESS|POS
A|SG|DN-LLINEN|ESS|SUP
A|SG|DN-MAINEN|POS|GEN
A|SG|DV-MATON|POS|GEN
A|SG|ELA|DN-MAINEN|POS
A|SG|ELA|DV-MATON|POS
A|SG|ESS|CMP
A|SG|ESS|POS
A|SG|ESS|POS|INTERR
A|SG|ESS|SUP
A|SG|GEN|CMP
A|SG|GEN|SUP
A|SG|ILL|DN-INEN|POS
A|SG|ILL|DV-MATON|POS
A|SG|POS|GEN
A|SG|POS|INTERR|GEN
A|SG|up|ESS|POS
A|SG|up|ESS|SUP
A|SUP|PCP2|PTV|PSS|PL
A|TRA|3|SG|POS
A|TRA|DN-INEN|POS|PL
A|TRA|DN-LLINEN|PL|CMP
A|TRA|DN-LLINEN|POS|PL
A|TRA|DN-LLINEN|SG|POS
A|TRA|DV-MATON|POS|PL
A|TRA|DV-VAINEN|PL|POS
A|TRA|POS|DN-LAINEN|PROP|SG
A|TRA|POS|PL
A|TRA|SG|CMP
A|TRA|SG|DN-INEN|POS
A|TRA|SG|DN-MAINEN|POS
A|TRA|SG|POS
A|TRA|SG|SUP
A|TRA|SG|kin|CMP
A|TRA|up|SG|POS
A|TRA|up|SG|SUP
A|TrunCo
A|TrunCo|up
A|kAAn|ADE|SG|POS
A|kin|SG|POS|GEN
A|st-cllq|NOM|SG|SUP
A|st-cllq|POS|PL|NOM
A|st-cllq|POS|PL|PTV
A|st-cllq|SG|POS|GEN
A|st-cllq|SG|POS|NOM
A|st-cllq|SG|POS|PTV
A|up
A|up|3|ADE|SUP|PL
A|up|ABL|3|PL|CMP
A|up|ADE|POS|PL
A|up|ADE|SG|POS
A|up|ELA|POS|PL
A|up|ELA|SG|POS
A|up|ESS|POS|DN-LAINEN|PROP|SG
A|up|GEN|PL|CMP
A|up|ILL|POS|DN-LLINEN|SG
A|up|POS|3|ADE|SG
A|up|POS|ADE|kin|SG
A|up|POS|DN-LAINEN|ADE|PROP|SG
A|up|POS|DN-LAINEN|INE|PROP|PL
A|up|POS|DN-LAINEN|PROP|GEN|PL
A|up|POS|DN-LAINEN|PROP|SG|GEN
A|up|POS|DN-LAINEN|PTV|PROP|SG
A|up|POS|DN-LLINEN|GEN|PL
A|up|POS|DN-LLINEN|INE|SG
A|up|POS|DN-LLINEN|PTV|PL
A|up|POS|DN-LLINEN|PTV|SG
A|up|POS|DN-LLINEN|SG|GEN
A|up|POS|DN-MAINEN|PTV|SG
A|up|POS|DN-TON|SG|GEN
A|up|POS|PL|GEN
A|up|SG|GEN|CMP
A|up|SG|GEN|SUP
A|up|SG|POS|GEN
A|up|TRA|POS|DN-LLINEN|SG
C
CMPR|C
CMT|POS|PCP1|ACT
CMT|up|N
COP|1SG|V|ACT|INE|INF2
COP|ACT|COND|PL1|V
COP|ACT|COND|PL3|V
COP|ACT|NEG|PRES|V
COP|ACT|PL1|PRES|V
COP|ACT|PL3|PRES|V
COP|ADE|INF3|V
COP|ELA|POS|PCP1|ACT|PL
COP|ELA|POS|PCP1|ACT|SG
COP|ILL|INF3|V
COP|ILL|POS|PCP1|ACT|SG
COP|INE|ACT|INF2|V
COP|INE|INF3|V
COP|NEG|ACT|COND|V
COP|NEG|V|PAST|ACT|PL
COP|NEG|V|PAST|ACT|SG
COP|NEG|V|kAAn|ACT|PRES
COP|NEG|V|kAAn|PAST|ACT|SG
COP|NEG|V|kin|ACT|PRES
COP|NOM|PCP2|POS|ACT|PL
COP|NOM|PCP2|POS|ACT|SG
COP|NOM|POS|PCP1|3|ACT|SG
COP|NOM|POS|PCP1|ACT|PL
COP|NOM|POS|PCP1|ACT|SG
COP|PCP2|POS|ACT|PTV|SG
COP|PCP2|POS|ACT|SG|GEN
COP|PL3|V|PAST|kin|ACT
COP|PL3|V|kO|PAST|ACT
COP|PL3|V|kin|ACT|PRES
COP|POS|PCP1|ACT|PTV|SG
COP|POS|PCP1|ACT|SG|GEN
COP|SG1|V|kin|ACT|PRES
COP|SG2|ACT|PRES|V
COP|SG3|ACT|COND|V
COP|SG3|ACT|POTN|V
COP|SG3|ACT|PRES|V
COP|SG3|V|COND|kin|ACT
COP|SG3|V|PAST|kin|ACT
COP|SG3|V|kO|ACT|PRES
COP|SG3|V|kO|COND|ACT
COP|SG3|V|kin|ACT|PRES
COP|TRA|POS|PCP1|ACT|PL
COP|V|up|IMPV|SG2|ACT
COP|kAAn|SG3|V|ACT|PRES
COP|up|PL1|V|ACT|PRES
COP|up|PL1|V|PAST|ACT
COP|up|PL3|V|kO|ACT|PRES
COP|up|SG1|V|ACT|PRES
COP|up|SG1|V|PAST|ACT
COP|up|SG1|V|kO|ACT|PRES
COP|up|SG3|V|ACT|PRES
COP|up|SG3|V|COND|ACT|kOhAn
COP|up|SG3|V|PAST|ACT
COP|up|SG3|V|kO|ACT|PRES
COP|up|SG3|V|kO|COND|ACT
COP|up|SG3|V|kO|PAST|ACT
COP|up|hAn|SG3|V|ACT|PRES
C|COORD
C|FORGN
C|NEGV|SG3|COORD
C|NEGV|SUB|PL1
C|PL3|NEGV|kA|COORD
C|SG1|NEGV|kA|COORD
C|SUB
C|SUB|NEGV|SG3|kO
C|SUB|SG1|NEGV|kO
C|SUB|kin
C|pA|SUB
C|st-arch|COORD
C|up|COORD
C|up|SUB
C|up|SUB|SG3|NEGV
C|up|SUB|kin
DA-US|PCP2|N|PTV|PSS|SG
DA-UUS|3|ABL|PL|N
DA-UUS|3|INE|SG|N
DA-UUS|3|N|DN-LLINEN|PTV|SG
DA-UUS|ABL|3|N|DN-LLINEN|SG
DA-UUS|ADE|SG|DV-VAINEN|N
DA-UUS|ADE|SG|N
DA-UUS|DN-LLINEN|ELA|SG|N
DA-UUS|DN-LLINEN|INE|PL|N
DA-UUS|DN-LLINEN|NOM|SG|N
DA-UUS|DN-LLINEN|PTV|PL|N
DA-UUS|DN-LLINEN|PTV|SG|N
DA-UUS|DN-LLINEN|SG|GEN|N
DA-UUS|DN-LLINEN|SG|ILL|N
DA-UUS|ELA|N|DN-LAINEN|SG|PROP
DA-UUS|ELA|PCP1|N|ACT|SG
DA-UUS|ELA|PL|N
DA-UUS|ELA|SG|DV-VAINEN|N
DA-UUS|ELA|SG|N
DA-UUS|ELA|SG|up|N
DA-UUS|GEN|PL|N
DA-UUS|GEN|SG|DV-VAINEN|N
DA-UUS|ILL|PCP1|N|ACT|SG
DA-UUS|ILL|PL|N
DA-UUS|ILL|SG|DV-MATON|N
DA-UUS|ILL|SG|DV-VAINEN|N
DA-UUS|ILL|SG|N
DA-UUS|ILL|up|SG|N
DA-UUS|INE|SG|DV-VAINEN|N
DA-UUS|INE|SG|N
DA-UUS|INE|SG|up|N
DA-UUS|NOM|PL|N
DA-UUS|NOM|SG|DV-VAINEN|N
DA-UUS|NOM|SG|N
DA-UUS|NOM|SG|up|N
DA-UUS|NOM|up|PL|N
DA-UUS|N|DN-LAINEN|SG|GEN|PROP
DA-UUS|PCP1|N|3|ACT|DV-U|PTV|SG
DA-UUS|PCP1|N|ACT|DV-U|SG|GEN
DA-UUS|PCP1|N|ACT|PTV|SG
DA-UUS|PCP1|N|ACT|SG|GEN
DA-UUS|PCP1|N|PTV|PSS|PL
DA-UUS|PCP1|N|PTV|PSS|SG
DA-UUS|PTV|PL|N
DA-UUS|PTV|SG|DV-VAINEN|N
DA-UUS|PTV|SG|N
DA-UUS|PTV|SG|up|N
DA-UUS|PTV|kin|PL|N
DA-UUS|PTV|up|PL|N
DA-UUS|SG|ABL|3|N
DA-UUS|SG|ABL|N
DA-UUS|SG|DV-MATON|ESS|N
DA-UUS|SG|ESS|N
DA-UUS|SG|GEN|N
DA-UUS|SG|NOM|DN-INEN|N
DA-UUS|SG|NOM|DV-MATON|N
DA-UUS|SG|PTV|DN-INEN|N
DA-UUS|SG|PTV|DV-MATON|N
DA-UUS|TrunCo|SG|GEN|N
DA-UUS|up|SG|GEN|N
DASH|PUNCT
DN-TON|ADV|POS|MAN
DN-TON|A|ELA|SG|POS
DN-TON|A|ILL|SG|POS
DN-TON|A|POS|PL|GEN
DN-TON|A|POS|PL|NOM
DN-TON|A|POS|PL|PTV
DN-TON|A|SG|ESS|POS
DN-TON|A|SG|POS|GEN
DN-TON|A|SG|POS|INE
DN-TON|A|SG|POS|NOM
DN-TON|A|SG|POS|PTV
DN-TON|A|SG|TRA|POS
DN-TON|DA-UUS|ELA|PL|N
DN-TON|DA-UUS|ELA|SG|N
DN-TON|DA-UUS|ILL|PL|N
DN-TON|DA-UUS|ILL|SG|N
DN-TON|DA-UUS|INE|PL|N
DN-TON|DA-UUS|INE|SG|N
DN-TON|DA-UUS|NOM|SG|N
DN-TON|DA-UUS|PTV|PL|N
DN-TON|DA-UUS|PTV|SG|N
DN-TON|DA-UUS|SG|GEN|N
DV-ELE|SG|GEN|N
DV-ILE|NEG|ACT|PAST|V|SG
DV-ILE|N|3|DV-U|PTV|SG
DV-ILE|PCP2|POS|PSS|GEN|PL
DV-ILE|PCP2|POS|PSS|SG|GEN
DV-ILE|POS|PCP1|ACT|INE|SG
DV-ILE|POS|PCP1|ACT|PTV|SG
DV-ILE|POS|PCP1|ACT|SG|GEN
DV-ILE|SG3|V|DV-TTA|ACT|PRES
DV-MATON|1PL|DA-UUS|N|SG|GEN
DV-MA|1SG|ALL|SG|N
DV-MA|3|ELA|PL|N
DV-MA|3|SG|GEN|N
DV-MA|ADE|SG|N
DV-MA|ALL|PL|N
DV-MA|ALL|SG|N
DV-MA|ELA|PL|N
DV-MA|ELA|SG|N
DV-MA|GEN|PL|N
DV-MA|ILL|1SG|PL|N
DV-MA|ILL|PL|N
DV-MA|ILL|SG|N
DV-MA|ILL|SG|3|N
DV-MA|INE|3|SG|N
DV-MA|INE|PL|N
DV-MA|INE|SG|N
DV-MA|NOM|1SG|SG|N
DV-MA|NOM|3|SG|N
DV-MA|NOM|PL|N
DV-MA|NOM|SG|N
DV-MA|PL|INS|N
DV-MA|PTV|1SG|SG|N
DV-MA|PTV|3|PL|N
DV-MA|PTV|3|PL|DV-TTA|N
DV-MA|PTV|3|SG|N
DV-MA|PTV|PL|N
DV-MA|PTV|SG|N
DV-MA|SG|ESS|N
DV-MA|SG|GEN|N
DV-MA|TRA|SG|N
DV-MA|up|PL|INS|N
DV-MINEN|GEN|PL|N
DV-NA|NOM|SG|N
DV-NA|PTV|SG|N
DV-NTAA|A|SG|POS|GEN
DV-NTAA|DV-US|SG|GEN|N
DV-NTAA|DV-US|up|N|PTV|SG
DV-NTAA|ILL|INF3|V
DV-NTAA|LAT|DV-ELE|INF1|V
DV-NTAA|LAT|INF1|V
DV-NTAA|NEG|ACT|PRES|V
DV-NTAA|NEG|V|PAST|ACT|SG
DV-NTAA|NOM|DV-US|SG|N
DV-NTAA|NOM|SG|DV-MINEN|N
DV-NTAA|PAST|ACT|PL3|V
DV-NTAA|PAST|PSS|PE4|V
DV-NTAA|PAST|SG3|ACT|V
DV-NTAA|PCP2|POS|PTV|PSS|SG
DV-NTAA|POS|PCP2|ACT|SG|GEN
DV-NTAA|PTV|DV-US|PL|N
DV-NTAA|PTV|SG|DV-MINEN|N
DV-NTAA|SG3|ACT|PRES|V
DV-NTAA|SG3|V|kin|ACT|PRES
DV-NTAA|SG|GEN|N
DV-NTAA|SG|ILL|DV-MINEN|N
DV-NTAA|TRA|SG|DV-MINEN|N
DV-NTAA|up|V|INE|PSS|INF2
DV-TTA|N|DV-MINEN|PTV|DV-ELE|SG
DV-TTA|N|DV-U|DV-ELE|SG|GEN
DV-US|3|ALL|PL|N
DV-US|3|ILL|PL|N
DV-US|3|SG|GEN|N
DV-US|ADE|PL|N
DV-US|ADE|SG|N
DV-US|ADE|SG|up|N
DV-US|ALL|PL|N
DV-US|CMT|3|N
DV-US|ELA|3|PL|N
DV-US|ELA|PL|N
DV-US|ELA|SG|DV-TTA|N
DV-US|ELA|SG|N
DV-US|ELA|SG|up|N
DV-US|ESS|PL|N
DV-US|GEN|PL|N
DV-US|ILL|N|TrunCo|3|SG
DV-US|ILL|PL|N
DV-US|INS|PL|N
DV-US|PL|ILL|DV-TTA|N
DV-US|SG|ALL|DV-TTA|N
DV-US|SG|ALL|N
DV-US|SG|GEN|DV-TTA|N
DV-US|SG|GEN|N
DV-US|SG|ILL|N
DV-US|up|DV-TTA|N|INE|SG
DV-US|up|DV-TTA|N|SG|GEN
DV-US|up|ESS|PL|N
DV-US|up|GEN|PL|N
DV-US|up|SG|GEN|N
DV-US|up|SG|ILL|N
DV-US|up|TRA|DV-TTA|N|SG
DV-UTTA|ELA|DV-US|PL|N
DV-U|ACT|COND|PL1|V
DV-U|ACT|INF2|INS|V
DV-U|ACT|PL1|PRES|V
DV-U|ACT|PL3|PRES|V
DV-U|ADE|DV-ELE|SG|N
DV-U|ADE|INF3|V
DV-U|ALL|DV-ELE|SG|N
DV-U|ALL|PL|N
DV-U|ALL|SG|N
DV-U|A|ELA|POS|PL
DV-U|A|ILL|POS|PL
DV-U|A|POS|PL|PTV
DV-U|DV-ELE|GEN|PL|N
DV-U|DV-ELE|SG|GEN|N
DV-U|DV-MA|ALL|SG|N
DV-U|DV-MA|PL|INE|N
DV-U|ELA|DV-ELE|SG|N
DV-U|ELA|PL|N
DV-U|ELA|SG|N
DV-U|ELA|SG|up|N
DV-U|GEN|PL|N
DV-U|ILL|INF3|V
DV-U|ILL|PL|N
DV-U|ILL|SG|N
DV-U|ILL|up|SG|N
DV-U|INE|ACT|INF2|V
DV-U|INE|DV-ELE|PL|N
DV-U|INE|DV-ELE|SG|N
DV-U|INE|INF3|V
DV-U|INE|N|SG|DV-ILE
DV-U|INE|PL|N
DV-U|INE|SG|N
DV-U|INE|up|PL|N
DV-U|INE|up|SG|N
DV-U|LAT|INF1|V
DV-U|NEG|ACT|COND|V
DV-U|NEG|ACT|PRES|V
DV-U|NOM|3|SG|N
DV-U|NOM|DV-ELE|PL|N
DV-U|NOM|DV-ELE|SG|N
DV-U|NOM|DV-SKELE|SG|N
DV-U|NOM|N|PL|DV-ILE
DV-U|NOM|N|SG|DV-ILE
DV-U|NOM|PL|N
DV-U|NOM|SG|DV-MINEN|N
DV-U|NOM|SG|DV-TTA|N
DV-U|NOM|SG|N
DV-U|NOM|TrunCo|SG|N
DV-U|NOM|up|PL|N
DV-U|NOM|up|SG|N
DV-U|N|SG|GEN|DV-ILE
DV-U|N|SG|GEN|DV-NEISUUS
DV-U|PAST|ACT|PL3|V
DV-U|PAST|PSS|PE4|V
DV-U|PAST|SG3|ACT|V
DV-U|PSS|PE4|PRES|V
DV-U|PTV|3|PL|N
DV-U|PTV|3|SG|N
DV-U|PTV|DV-ELE|PL|N
DV-U|PTV|DV-ELE|SG|N
DV-U|PTV|DV-JA|PL|N
DV-U|PTV|DV-SKELE|SG|N
DV-U|PTV|N|PL|DV-ILE
DV-U|PTV|N|SG|DV-NEISUUS
DV-U|PTV|PL|N
DV-U|PTV|SG|DV-MINEN|N
DV-U|PTV|SG|N
DV-U|PTV|up|PL|N
DV-U|PTV|up|SG|N
DV-U|SG3|ACT|COND|V
DV-U|SG3|ACT|PRES|V
DV-U|SG|DV-MINEN|GEN|N
DV-U|SG|ELA|DV-MINEN|N
DV-U|SG|GEN|N
DV-U|SG|ILL|DV-MINEN|N
DV-U|SG|N|ABL|DV-ILE
DV-U|SG|up|ESS|N
DV-U|TRA|SG|DV-MINEN|N
DV-U|TRA|SG|N
DV-U|TRA|up|SG|N
DV-U|up|SG|GEN|N
ELA|1SG|PL|N
ELA|DV-JA|PL|N
ELA|INF3|V
ELA|NUM|SG
ELA|NUM|SG|up
ELA|N|3|PL|DA-US
ELA|N|PL|DA-US
ELA|N|PL|st-slang
ELA|N|SG|DA-US
ELA|N|SG|DV-NEISUUS
ELA|N|SG|up|DA-US
ELA|N|SG|up|PROP
ELA|N|up|PL|PROP
ELA|PCP2|DV-TTA|POS|PSS|DV-ELE|PL
ELA|PCP2|N|DA-US|PSS|SG
ELA|PL|DV-JA|DV-TTA|N
ELA|PL|N
ELA|PL|POS|PCP1|ACT
ELA|POS|PCP1|ACT|DV-U|SG
ELA|POS|PCP2|ACT|DV-U|PL
ELA|POS|PCP2|ACT|DV-U|SG
ELA|SG|1PL|N
ELA|SG|2PL|N
ELA|SG|DV-JA|N
ELA|SG|N
ELA|SG|POS|PCP1|ACT
ELA|SG|up|N
ELA|up|PL|N
ESS|DV-ILE|PCP2|POS|PSS|SG
ESS|DV-ILE|POS|PCP1|DV-TTA|ACT|PL
ESS|DV-JA|DV-TTA|N|DV-ELE|PL
ESS|DV-JA|PL|N
ESS|PCP2|POS|PSS|DV-ELE|SG
ESS|PL|N
ESS|POS|PCP2|DV-UTU|ACT|SG
ESS|SG|DV-MINEN|N
FORGN
FORGN|ART
FORGN|ART|up
FORGN|N
FORGN|SG|GEN|N
FORGN|up
FORGN|up|N
GEN|3|DV-JA|PL|N
GEN|3|SG|DV-JA|N
GEN|DV-ELE|SG|DV-JA|N
GEN|DV-JA|PL|N
GEN|N|DV-JA|PL|DV-ILE
GEN|PL|DV-JA|DV-TTA|N
GEN|PL|N
GEN|PL|POS|PCP1|ACT
GEN|SG|DV-JA|DV-TTA|N
GEN|SG|DV-JA|N
GEN|SG|POS|PCP1|ACT
GEN|up|DV-JA|PL|N
GEN|up|SG|DV-JA|N
ILL|1PL|PL|N
ILL|1SG|PL|N
ILL|2SG|PL|N
ILL|3|PL|N
ILL|DV-ELE|INF3|V
ILL|DV-JA|PL|N
ILL|DV-MINEN|PL|N
ILL|DV-SKELE|INF3|V
ILL|DV-TTA|N|DV-U|DV-ELE|PL
ILL|INF3|DV-TTA|V
ILL|INF3|V
ILL|NUM|PL
ILL|NUM|SG
ILL|NUM|SG|up
ILL|N|3|DV-MINEN|DV-U|SG
ILL|N|PL|DA-US
ILL|N|SG|3|DA-US
ILL|N|SG|DA-US
ILL|N|SG|DV-ILE
ILL|N|SG|PROP
ILL|N|SG|up|PROP
ILL|N|up|PL|PROP
ILL|PL|DV-JA|DV-TTA|N
ILL|PL|DV-TTA|N
ILL|PL|N
ILL|PL|POS|PCP1|ACT
ILL|POS|PCP1|ACT|DV-U|SG
ILL|SG|1PL|N
ILL|SG|3|N
ILL|SG|DV-JA|DV-TTA|N
ILL|SG|DV-JA|N
ILL|SG|DV-TTA|N
ILL|SG|N
ILL|SG|POS|PCP1|ACT
ILL|SG|kin|N
ILL|V|INF3|DV-ILE
ILL|up|INF3|V
ILL|up|PL|N
ILL|up|SG|3|N
ILL|up|SG|DV-JA|N
ILL|up|SG|N
INE|1PL|PL|N
INE|3|ACT|INF2|V
INE|3|DV-NTA|PL|N
INE|3|N|SG|DA-US
INE|3|PL|N
INE|3|SG|N
INE|3|up|PL|N
INE|3|up|SG|N
INE|ACT|INF2|1PL|V
INE|ACT|INF2|DV-TTA|V
INE|ACT|INF2|V
INE|DV-ELE|INF3|V
INE|DV-JA|PL|N
INE|DV-US|3|PL|N
INE|DV-US|PL|DV-TTA|N
INE|DV-US|PL|N
INE|DV-US|SG|3|N
INE|DV-US|SG|DV-TTA|N
INE|DV-US|SG|N
INE|DV-US|TrunCo|SG|N
INE|DV-US|up|PL|N
INE|DV-US|up|SG|N
INE|DV-UTU|PL|N
INE|FORGN|SG|up|N
INE|INF3|V
INE|NUM|SG
INE|NUM|SG|up
INE|N|SG|DA-US
INE|N|SG|PROP
INE|N|SG|up|DA-US
INE|N|SG|up|PROP
INE|N|up|PL|DV-ILE
INE|N|up|PL|PROP
INE|ORD|NUM|SG
INE|ORD|NUM|SG|up
INE|PL|N
INE|PL|POS|PCP1|ACT
INE|PSP
INE|SG|1PL|N
INE|SG|DV-JA|N
INE|SG|DV-MINEN|N
INE|SG|DV-NTA|N
INE|SG|DV-NTI|N
INE|SG|DV-TTA|N
INE|SG|DV-UTU|DV-MINEN|N
INE|SG|N
INE|SG|POS|PCP1|ACT
INE|SG|kin|N
INE|SG|up|DV-MINEN|N
INE|SG|up|DV-NTA|N
INE|TrunCo|PL|N
INE|TrunCo|SG|N
INE|kin|PL|N
INE|up|INF3|V
INE|up|PL|N
INE|up|SG|ABBR
INE|up|SG|DV-TTA|N
INE|up|SG|N
INE|up|SG|kin|N
INF3|ABE|1PL|V
INF3|ABE|V
INS|PL|N
INS|kin|PL|N
INS|up|PL|N
INTJ
LAT|COP|INF1|V
LAT|DV-ELE|INF1|DV-TTA|V
LAT|DV-ELE|INF1|V
LAT|DV-UTU|INF1|V
LAT|INF1|DV-TTA|V
LAT|INF1|V
LAT|V|INF1|DV-ILE
LAT|kAAn|INF1|V
LAT|kin|INF1|V
LAT|st-cllq|INF1|V
LAT|st-cllq|V|INF1|DV-ILE
MAN|COP|ACT|INF2|V
NEGV|PL1|V
NEG|ACT|COND|DV-TTA|V
NEG|ACT|COND|V
NEG|ACT|COND|kAAn|V
NEG|ACT|PRES|DV-TTA|V
NEG|ACT|PRES|V
NEG|ACT|kAAn|PRES|V
NEG|V|DV-TTA|PAST|ACT|SG
NEG|V|PAST|ACT|DV-ELE|SG
NEG|V|PAST|ACT|DV-U|PL
NEG|V|PAST|ACT|DV-U|SG
NEG|V|kAAn|DV-TTA|COND|ACT
NEG|V|kAAn|PAST|ACT|SG
NOM|1PL|PL|N
NOM|1SG|DA-UUS|PCP1|N|PSS|SG
NOM|1SG|POS|PCP1|ACT|SG
NOM|2SG|SG|DV-JA|N
NOM|2SG|SG|N
NOM|2SG|SG|kin|N
NOM|3|N|SG|DA-US
NOM|3|PL|N
NOM|3|SG|DV-JA|N
NOM|3|SG|N
NOM|3|SG|kin|N
NOM|3|TrunCo|SG|N
NOM|3|up|SG|ABBR
NOM|3|up|SG|N
NOM|DA-UUS|DV-VAINEN|N|3|SG
NOM|DA-UUS|N|DN-LAINEN|SG|PROP
NOM|DA-UUS|PCP1|N|ACT|SG
NOM|DA-UUS|PCP1|N|PSS|SG
NOM|DV-ELE|SG|DV-JA|N
NOM|DV-ILE|PCP2|POS|PSS|SG
NOM|DV-ILE|POS|PCP2|ACT|SG
NOM|DV-JA|PL|N
NOM|DV-MINEN|PL|N
NOM|DV-NTA|PL|N
NOM|DV-US|3|PL|N
NOM|DV-US|DV-TTA|N|TrunCo|SG
NOM|DV-US|PL|DV-TTA|N
NOM|DV-US|PL|N
NOM|DV-US|SG|2PL|N
NOM|DV-US|SG|3|N
NOM|DV-US|SG|DV-TTA|N
NOM|DV-US|SG|N
NOM|DV-US|TrunCo|SG|N
NOM|DV-US|up|DV-TTA|N|SG
NOM|DV-US|up|N|TrunCo|SG
NOM|DV-US|up|PL|N
NOM|DV-US|up|SG|N
NOM|DV-UTU|DV-MINEN|PL|N
NOM|DV-UTU|SG|N
NOM|FORGN|SG|N
NOM|FORGN|SG|up|N
NOM|NUM|PL
NOM|NUM|SG
NOM|NUM|SG|up
NOM|N|3|DV-U|DV-ELE|SG
NOM|N|DN-LAINEN|PL|PROP
NOM|N|PL|DA-US
NOM|N|SG|DA-US
NOM|N|SG|DV-ILE
NOM|N|SG|DV-JA|st-slang
NOM|N|SG|PROP
NOM|N|SG|st-slang
NOM|N|SG|up|DA-US
NOM|N|SG|up|DV-NEISUUS
NOM|N|SG|up|PROP
NOM|N|SG|up|st-slang
NOM|N|up|PL|PROP
NOM|ORD|NUM|PL
NOM|ORD|NUM|SG
NOM|ORD|NUM|SG|up
NOM|ORD|NUM|up|PL
NOM|PCP2|DV-TTA|POS|PSS|DV-ELE|SG
NOM|PCP2|DV-TTA|POS|PSS|PL
NOM|PCP2|DV-TTA|POS|PSS|SG
NOM|PCP2|N|DA-US|PSS|SG
NOM|PCP2|POS|DV-U|PSS|SG
NOM|PCP2|POS|PSS|DV-ELE|SG
NOM|PL|DV-JA|DV-TTA|N
NOM|PL|DV-TTA|N
NOM|PL|N
NOM|PL|POS|PCP1|ACT
NOM|POS|DV-TTA|PCP2|ACT|DV-ELE|SG
NOM|POS|DV-TTA|PCP2|ACT|PL
NOM|POS|DV-TTA|PCP2|ACT|SG
NOM|POS|PCP1|3|ACT|SG
NOM|POS|PCP1|ACT|DV-ELE|SG
NOM|POS|PCP1|ACT|DV-U|PL
NOM|POS|PCP1|ACT|DV-U|SG
NOM|POS|PCP1|DV-TTA|ACT|PL
NOM|POS|PCP1|DV-TTA|ACT|SG
NOM|POS|PCP1|DV-TTA|PSS|DV-ELE|PL
NOM|POS|PCP1|DV-TTA|PSS|SG
NOM|POS|PCP1|DV-UTU|ACT|PL
NOM|POS|PCP1|st-hi|ACT|SG
NOM|POS|PCP2|3|ACT|DV-U|SG
NOM|POS|PCP2|3|ACT|SG
NOM|POS|PCP2|ACT|DV-ELE|PL
NOM|POS|PCP2|ACT|DV-ELE|SG
NOM|POS|PCP2|ACT|DV-U|PL
NOM|POS|PCP2|ACT|DV-U|SG
NOM|POS|PCP2|DV-UTU|ACT|PL
NOM|POS|PCP2|DV-UTU|ACT|SG
NOM|POS|PCP2|kin|ACT|DV-U|SG
NOM|POS|PCP2|kin|ACT|SG
NOM|SG|1PL|N
NOM|SG|ABBR
NOM|SG|ABBR|TrunCo
NOM|SG|DV-JA|DN-TAR|N
NOM|SG|DV-JA|DV-TTA|N
NOM|SG|DV-JA|N
NOM|SG|DV-MINEN|3|N
NOM|SG|DV-MINEN|N
NOM|SG|DV-NTA|1PL|N
NOM|SG|DV-NTA|3|N
NOM|SG|DV-NTA|N
NOM|SG|DV-NTI|N
NOM|SG|DV-NTI|kAAn|N
NOM|SG|DV-TTA|N
NOM|SG|DV-UTU|DV-MINEN|N
NOM|SG|N
NOM|SG|POS|PCP1|ACT
NOM|SG|TrunCo|DV-MINEN|N
NOM|SG|TrunCo|DV-NTA|N
NOM|SG|TrunCo|DV-NTI|N
NOM|SG|hAn|N
NOM|SG|kin|N
NOM|SG|up|DV-MINEN|N
NOM|SG|up|DV-NTA|N
NOM|SG|up|DV-NTI|N
NOM|SG|up|st-hi|N
NOM|TrunCo|N|SG|DA-US
NOM|TrunCo|PL|N
NOM|TrunCo|SG|DV-JA|N
NOM|TrunCo|SG|N
NOM|TrunCo|up|SG|N
NOM|kin|DV-JA|PL|N
NOM|kin|PL|N
NOM|st-cllq|PCP2|POS|ACT|SG
NOM|st-cllq|PCP2|POS|PSS|SG
NOM|up|1PL|N|PROP|SG
NOM|up|DA-UUS|DV-VAINEN|N|SG
NOM|up|DA-UUS|N|DN-INEN|SG
NOM|up|DA-UUS|N|DN-LLINEN|SG
NOM|up|DA-UUS|N|DN-TON|PL
NOM|up|DA-UUS|N|DN-TON|SG
NOM|up|DA-UUS|PCP1|N|ACT|SG
NOM|up|DV-ILE|N|DV-U|SG
NOM|up|DV-ILE|PCP2|POS|PSS|SG
NOM|up|DV-JA|N|DV-UTU|SG
NOM|up|DV-JA|PL|N
NOM|up|N|3|PROP|SG
NOM|up|N|DV-MINEN|DV-U|SG
NOM|up|N|DV-U|DV-ELE|PL
NOM|up|N|DV-U|DV-ELE|SG
NOM|up|N|FORGN|PROP|PL
NOM|up|N|FORGN|PROP|SG
NOM|up|N|TrunCo|PROP|SG
NOM|up|N|kin|PROP|SG
NOM|up|PCP2|POS|PSS|PL
NOM|up|PCP2|POS|PSS|SG
NOM|up|PL|N
NOM|up|POS|PCP1|ACT|DV-U|SG
NOM|up|POS|PCP1|ACT|SG
NOM|up|POS|PCP1|PSS|SG
NOM|up|POS|PCP1|kin|ACT|SG
NOM|up|POS|PCP2|ACT|PL
NOM|up|POS|PCP2|ACT|SG
NOM|up|PRON|kin|SG|DEM
NOM|up|SG|ABBR
NOM|up|SG|DV-JA|N
NOM|up|SG|DV-TTA|N
NOM|up|SG|N
NOM|up|SG|hAn|N
NOM|up|SG|kin|N
NOM|up|SG|st-arch|N
NOM|up|kAAn|N|PROP|SG
NOM|up|kin|PL|N
NOM|up|st-cllq|N|TrunCo|SG
NON-TWOL
NUM|GEN|PL
NUM|SG|GEN
N|3|DV-U|INE|DV-ELE|SG
N|ABL|up|PL|PROP
N|DN-LAINEN|SG|ALL|PROP
N|DN-LAINEN|SG|GEN|PROP
N|FORGN|up|PROP
N|GEN|PL|DA-US
N|SG|GEN|DA-US
N|SG|GEN|DV-ILE
N|SG|GEN|DV-NEISUUS
N|SG|GEN|PROP
N|SG|GEN|st-derog
N|up|PROP
ORD|NUM|SG|ALL
ORD|NUM|SG|GEN
ORD|NUM|SG|ILL
PAST|3|ACT|TEMP|V
PAST|ACT|PL1|V
PAST|ACT|PL3|DV-TTA|V
PAST|ACT|PL3|V
PAST|ACT|PL3|kin|V
PAST|ACT|SG2|V
PAST|ACT|TEMP|DV-TTA|V
PAST|ACT|TEMP|V
PAST|ACT|up|PL1|V
PAST|ACT|up|TEMP|V
PAST|COP|ACT|PL3|V
PAST|COP|ACT|SG1|V
PAST|COP|PSS|NEG|V
PAST|COP|SG3|ACT|V
PAST|DV-ELE|PL1|ACT|V
PAST|DV-ELE|PL3|ACT|V
PAST|DV-SKELE|PL3|ACT|V
PAST|DV-UTU|PL3|ACT|V
PAST|NEG|ACT|PL|V
PAST|NEG|ACT|SG|V
PAST|PSS|DV-ELE|PE4|V
PAST|PSS|NEG|V
PAST|PSS|PE4|DV-TTA|V
PAST|PSS|PE4|V
PAST|PSS|PE4|kO|V
PAST|PSS|PE4|kin|V
PAST|PSS|REF|V
PAST|PSS|V|PE4|DV-ILE
PAST|PSS|up|REF|V
PAST|SG1|ACT|DV-TTA|V
PAST|SG1|ACT|V
PAST|SG1|ACT|kin|V
PAST|SG1|ACT|up|V
PAST|SG1|DV-ELE|ACT|V
PAST|SG1|V|ACT|DV-ILE
PAST|SG3|ACT|DV-TTA|V
PAST|SG3|ACT|V
PAST|SG3|ACT|hAn|V
PAST|SG3|ACT|kin|V
PAST|SG3|ACT|up|V
PAST|SG3|DV-ELE|ACT|V
PAST|SG3|DV-UTU|ACT|V
PAST|SG3|V|ACT|DV-ILE
PAST|V|PL3|ACT|DV-ILE
PAST|kAAn|SG3|ACT|V
PAST|st-cllq|ACT|PL1|V
PAST|st-cllq|ACT|PL2|V
PAST|st-cllq|SG3|ACT|V
PCP2|DV-TTA|POS|ADE|PSS|SG
PCP2|DV-TTA|POS|PSS|DV-ELE|GEN|PL
PCP2|DV-TTA|POS|PTV|PSS|SG
PCP2|N|DA-US|PSS|SG|GEN
PCP2|POS|3|PTV|DV-U|PSS|SG
PCP2|POS|3|PTV|PSS|SG
PCP2|POS|DV-UTU|PTV|PSS|SG
PCP2|POS|PTV|DV-U|PSS|SG
PE4|COP|PSS|PRES|V
PE4|DV-TTA|PAST|V|PSS|DV-ELE
PE4|POTN|PSS|V
PE4|PSS|COND|V
PE4|PSS|COND|kin|V
PE4|PSS|DV-ELE|PRES|V
PE4|PSS|PRES|DV-TTA|V
PE4|PSS|PRES|V
PE4|PSS|V|PRES|DV-ILE
PE4|PSS|kin|PRES|V
PE4|PSS|up|PRES|V
PE4|st-cllq|PSS|PRES|V
PERS|PRON|ABL|PL
PERS|PRON|ADE|PL
PERS|PRON|ADE|SG
PERS|PRON|ADE|SG|up
PERS|PRON|ADE|up|PL
PERS|PRON|ALL|PL
PERS|PRON|ALL|SG
PERS|PRON|ALL|up|PL
PERS|PRON|ALL|up|SG
PERS|PRON|ELA|PL
PERS|PRON|ELA|SG
PERS|PRON|GEN|PL
PERS|PRON|ILL|PL
PERS|PRON|ILL|SG
PERS|PRON|PL|ACC
PERS|PRON|PL|NOM
PERS|PRON|PL|PTV
PERS|PRON|SG|ABL
PERS|PRON|SG|ACC
PERS|PRON|SG|GEN
PERS|PRON|SG|GEN|kin
PERS|PRON|SG|INE
PERS|PRON|SG|NOM
PERS|PRON|SG|PTV
PERS|PRON|SG|kin|NOM
PERS|PRON|kin|PL|NOM
PERS|PRON|pA|SG|NOM
PERS|PRON|up|GEN|PL
PERS|PRON|up|PL|NOM
PERS|PRON|up|PL|PTV
PERS|PRON|up|SG|ACC
PERS|PRON|up|SG|GEN
PERS|PRON|up|SG|NOM
PERS|PRON|up|SG|PTV
PL3|ACT|COND|V
PL3|ACT|COND|kin|V
PL3|C|NEGV|SUB
PL3|NEGV|V
PL3|V|kO|ACT|DV-U|PRES
PL|ABL|POS|PCP1|ACT
PL|GEN|DV-TTA|N
POS|ADE|PCP2|PL|ACT
POS|ADE|SG|PCP2|ACT
POS|ALL|PCP2|PL|ACT
POS|ALL|SG|PCP2|ACT
POS|DV-TTA|PCP2|ACT|SG|GEN
POS|ELA|PCP2|PL|ACT
POS|ELA|SG|PCP2|ACT
POS|ESS|PCP2|PL|ACT
POS|GEN|PCP2|PL|ACT
POS|GEN|SG|PCP2|ACT
POS|ILL|SG|PCP2|ACT
POS|INE|PCP2|PL|ACT
POS|INE|SG|PCP2|ACT
POS|NOM|PCP2|PL|ACT
POS|NOM|SG|PCP2|ACT
POS|PCP1|ACT|DV-ELE|SG|GEN
POS|PCP1|ACT|DV-U|INE|SG
POS|PCP1|ACT|DV-U|SG|GEN
POS|PCP1|DV-TTA|ACT|PTV|SG
POS|PCP1|DV-TTA|ACT|SG|GEN
POS|PCP1|DV-TTA|PSS|SG|GEN
POS|PCP1|DV-UTU|ACT|PTV|SG
POS|PCP1|DV-UTU|ACT|SG|GEN
POS|PCP2|ACT|DV-ELE|SG|GEN
POS|PCP2|ACT|DV-U|GEN|PL
POS|PCP2|ACT|DV-U|INE|PL
POS|PCP2|ACT|DV-U|INE|SG
POS|PCP2|ACT|DV-U|PTV|PL
POS|PCP2|ACT|DV-U|PTV|SG
POS|PCP2|ACT|DV-U|SG|GEN
POS|PCP2|DV-UTU|ACT|PTV|SG
POS|PTV|PCP2|PL|ACT
POS|PTV|SG|PCP2|ACT
POS|SG|ABL|PCP2|ACT
POS|SG|ESS|PCP2|ACT
POTN|ACT|PL3|V
PP
PP|3
PP|ADE|3
PP|FORGN
PP|kin
PP|up
PRON|3|REFL/Q|SG|INE
PRON|3|REFL/Q|SG|NOM
PRON|3|REFL/Q|SG|PTV
PRON|ADE|DEM|PL
PRON|ADE|DEM|PL|kin
PRON|ADE|REFL/Q|SG|3
PRON|ADE|SG|DEM
PRON|ADE|SG|DEM|kin
PRON|ADE|SG|REL
PRON|ALL|DEM|PL
PRON|ALL|REFL/Q|SG|1PL
PRON|ALL|REFL/Q|SG|3
PRON|ALL|REFL/Q|SG|kin
PRON|ALL|SG|DEM
PRON|ALL|SG|DEM|kin
PRON|ALL|SG|REL
PRON|DEM|PL|GEN
PRON|DEM|PL|INE
PRON|DEM|PL|NOM
PRON|DEM|PL|PTV
PRON|ELA|DEM|PL
PRON|ELA|REFL/Q|SG|1PL
PRON|ELA|REFL/Q|SG|3
PRON|ELA|REL
PRON|ELA|SG|DEM
PRON|ELA|SG|DEM|kin
PRON|ELA|SG|REL
PRON|ELA|up|REL
PRON|GEN|REL
PRON|GEN|REL|PL
PRON|ILL|DEM|PL
PRON|ILL|PL|REL
PRON|ILL|REFL/Q|SG|1PL
PRON|ILL|REFL/Q|SG|3
PRON|ILL|REL
PRON|ILL|SG|DEM
PRON|ILL|SG|REL
PRON|ILL|up|DEM|PL
PRON|ILL|up|REL
PRON|ILL|up|SG|DEM
PRON|INTG|SG|NOM
PRON|INTG|SG|s|NOM
PRON|INTG|pA|SG|NOM
PRON|INTG|s|PTV
PRON|PL|REL|NOM
PRON|PL|REL|PTV
PRON|REFL/Q|SG|1PL|PTV
PRON|REFL/Q|SG|NOM
PRON|REFL/Q|SG|kin|NOM
PRON|REFL/Q|SG|up|NOM
PRON|REL|INE
PRON|REL|PTV
PRON|SG|ABL|DEM
PRON|SG|DEM|GEN
PRON|SG|DEM|INE
PRON|SG|DEM|NOM
PRON|SG|DEM|PTV
PRON|SG|DEM|hAn|NOM
PRON|SG|ESS|DEM
PRON|SG|ESS|DEM|kAAn
PRON|SG|ESS|DEM|kin
PRON|SG|GEN|REL
PRON|SG|REFL/Q|ABL|3
PRON|SG|REFL/Q|ESS|3
PRON|SG|REL|INE
PRON|SG|REL|NOM
PRON|SG|REL|PTV
PRON|SG|up|ESS|DEM
PRON|kin|DEM|PL|INE
PRON|kin|DEM|PL|PTV
PRON|kin|SG|DEM|NOM
PRON|up|DEM|PL|GEN
PRON|up|DEM|PL|INE
PRON|up|DEM|PL|NOM
PRON|up|DEM|PL|PTV
PRON|up|REL|PTV
PRON|up|SG|DEM|GEN
PRON|up|SG|DEM|INE
PRON|up|SG|DEM|NOM
PRON|up|SG|DEM|PTV
PRON|up|SG|REL|NOM
PSP
PSP|1SG|ILL
PSP|3
PSP|ADE|1SG
PSP|ALL|3
PSP|ILL|1PL
PSP|ILL|3
PSP|up|1SG|ALL
PSS|ADE|PCP2|PL|POS
PSS|ADE|POS|PCP1|PL
PSS|ADE|SG|PCP2|POS
PSS|ADE|SG|POS|PCP1
PSS|ALL|SG|PCP2|POS
PSS|ALL|SG|POS|PCP1
PSS|DV-ELE|NEG|PRES|V
PSS|ELA|PCP2|PL|POS
PSS|ELA|SG|PCP2|POS
PSS|ELA|SG|POS|PCP1
PSS|ESS|PCP2|PL|POS
PSS|GEN|PCP2|PL|POS
PSS|GEN|SG|PCP2|POS
PSS|ILL|PCP2|PL|POS
PSS|ILL|SG|PCP2|POS
PSS|ILL|SG|POS|PCP1
PSS|INE|INF2|V
PSS|INE|PCP2|PL|POS
PSS|INE|SG|PCP2|POS
PSS|NEG|COND|V
PSS|NEG|PRES|V
PSS|NOM|PCP2|PL|POS
PSS|NOM|SG|PCP2|POS
PSS|PL|POS|PCP1|INE
PSS|PL|POS|PCP1|NOM
PSS|PL|POS|PCP1|PTV
PSS|PTV|PCP2|PL|POS
PSS|PTV|SG|PCP2|POS
PSS|REF|PRES|V
PSS|SG|ABL|PCP2|POS
PSS|SG|ESS|PCP2|POS
PSS|SG|ESS|POS|PCP1
PSS|SG|POS|PCP1|GEN
PSS|SG|POS|PCP1|INE
PSS|SG|POS|PCP1|NOM
PSS|SG|POS|PCP1|PTV
PSS|V|NEG|PRES|DV-ILE
PTV|1PL|PL|N
PTV|1SG|PL|N
PTV|3|DV-ELE|PL|N
PTV|3|N|SG|DA-US
PTV|3|PL|N
PTV|3|SG|N
PTV|3|TrunCo|SG|N
PTV|DV-ELE|SG|N
PTV|DV-JA|PL|N
PTV|DV-MINEN|PL|N
PTV|DV-NTI|PL|N
PTV|DV-US|3|PL|N
PTV|DV-US|PL|DV-TTA|N
PTV|DV-US|PL|N
PTV|DV-US|SG|DV-TTA|N
PTV|DV-US|SG|N
PTV|DV-US|up|PL|N
PTV|DV-US|up|SG|N
PTV|DV-UTU|SG|N
PTV|FORGN|PL|N
PTV|FORGN|SG|up|N
PTV|NUM|PL
PTV|NUM|SG
PTV|NUM|SG|up
PTV|N|DN-LAINEN|SG|PROP
PTV|N|DV-JA|PL|st-slang
PTV|N|PL|DA-US
PTV|N|PL|DV-ILE
PTV|N|SG|DA-US
PTV|N|SG|up|PROP
PTV|ORD|NUM|PL
PTV|ORD|NUM|SG
PTV|ORD|NUM|SG|up
PTV|PL|DV-JA|DV-TTA|N
PTV|PL|DV-TTA|N
PTV|PL|N
PTV|PL|POS|PCP1|ACT
PTV|SG|1PL|N
PTV|SG|DV-ELE|DV-MINEN|N
PTV|SG|DV-JA|DV-TTA|N
PTV|SG|DV-JA|N
PTV|SG|DV-MINEN|3|N
PTV|SG|DV-MINEN|N
PTV|SG|DV-NTA|N
PTV|SG|DV-NTI|N
PTV|SG|DV-TTA|N
PTV|SG|DV-UTU|DV-MINEN|N
PTV|SG|N
PTV|SG|POS|PCP1|ACT
PTV|SG|kin|N
PTV|SG|up|DV-NTA|N
PTV|TrunCo|PL|N
PTV|TrunCo|SG|N
PTV|up|DV-JA|PL|N
PTV|up|PL|N
PTV|up|SG|1PL|N
PTV|up|SG|ABBR
PTV|up|SG|N
PUNCT
PUNCT|EMDASH
PUNCT|ENDASH
PUNCT|QUOTE
Q|PRON|1PL|PL|PTV
Q|PRON|3|ABL|PL
Q|PRON|3|ELA|PL
Q|PRON|3|GEN|PL
Q|PRON|3|PL|PTV
Q|PRON|ABL|PL
Q|PRON|ADE|PL
Q|PRON|ADE|SG
Q|PRON|ADE|SG|kin
Q|PRON|ADE|SG|up
Q|PRON|ALL|3|PL
Q|PRON|ALL|PL
Q|PRON|ALL|SG
Q|PRON|ELA|PL
Q|PRON|ELA|SG
Q|PRON|ELA|SG|up
Q|PRON|ELA|up|PL
Q|PRON|ESS|PL
Q|PRON|GEN|PL
Q|PRON|GEN|PL|kin
Q|PRON|ILL|3|PL
Q|PRON|ILL|PL
Q|PRON|ILL|SG
Q|PRON|ILL|SG|kin
Q|PRON|ILL|up|PL
Q|PRON|ILL|up|SG
Q|PRON|NOM
Q|PRON|PL|INE
Q|PRON|PL|NOM
Q|PRON|PL|PTV
Q|PRON|SG|ABL
Q|PRON|SG|ESS
Q|PRON|SG|GEN
Q|PRON|SG|INE
Q|PRON|SG|NOM
Q|PRON|SG|PTV
Q|PRON|SG|TRA
Q|PRON|SG|kAAn|PTV
Q|PRON|SG|kin|NOM
Q|PRON|SG|up|ESS
Q|PRON|SG|up|TRA
Q|PRON|kin|PL|INE
Q|PRON|kin|PL|PTV
Q|PRON|up|GEN|PL
Q|PRON|up|NOM
Q|PRON|up|PL|INE
Q|PRON|up|PL|INS
Q|PRON|up|PL|NOM
Q|PRON|up|PL|PTV
Q|PRON|up|SG|GEN
Q|PRON|up|SG|INE
Q|PRON|up|SG|NOM
Q|PRON|up|SG|PTV
Q|PRON|up|hAn|NOM
REFL/Q|1SG|PRON|ADE|up|SG
SG1|ACT|COND|V
SG1|ACT|COND|kin|V
SG1|ACT|COND|up|V
SG1|ACT|PRES|V
SG1|ACT|up|PRES|V
SG1|COP|ACT|COND|V
SG1|COP|ACT|PRES|V
SG1|C|NEGV|SUB|V
SG1|NEGV|V
SG1|POTN|ACT|up|V
SG1|V|PAST|kin|ACT|DV-ELE
SG1|st-cllq|ACT|PRES|V
SG1|up|NEGV|V
SG2|ACT|PRES|V
SG2|ACT|up|PRES|V
SG2|NEGV|V
SG2|NEGV|up|V
SG3|ACT|COND|V
SG3|ACT|COND|up|V
SG3|ACT|PRES|DV-TTA|V
SG3|ACT|PRES|V
SG3|ACT|hAn|PRES|V
SG3|ACT|kO|PRES|V
SG3|ACT|kin|PRES|V
SG3|ACT|up|PRES|V
SG3|C|NEGV|SUB|V
SG3|NEGV|V
SG3|V|DV-TTA|PAST|ACT|DV-ELE
SG3|up|NEGV|V
SG|3|ABL|N
SG|3|ADE|DV-NTA|N
SG|3|DV-NTA|GEN|N
SG|3|ELA|DV-MINEN|N
SG|3|ESS|DV-JA|N
SG|3|ESS|N
SG|3|N|ABL|DA-US
SG|3|up|ABL|N
SG|ABBR|GEN
SG|ABE|N
SG|ABL|DV-JA|N
SG|ABL|N
SG|ABL|POS|PCP1|ACT
SG|ADE|DV-MINEN|N
SG|ADE|DV-NTA|up|N
SG|ADE|DV-NTI|N
SG|ALL|DV-MINEN|N
SG|ALL|DV-NTA|N
SG|ALL|up|DV-MINEN|N
SG|ALL|up|st-hi|N
SG|DV-ELE|ESS|DV-JA|N
SG|DV-MINEN|GEN|N
SG|DV-NTA|GEN|N
SG|DV-NTI|GEN|N
SG|DV-US|ABL|3|N
SG|DV-US|ESS|N
SG|DV-US|up|ABL|N
SG|DV-US|up|ESS|N
SG|DV-UTU|DV-MINEN|GEN|N
SG|ELA|DV-MINEN|N
SG|ELA|DV-NTA|N
SG|ELA|DV-NTI|N
SG|ELA|DV-NTI|up|N
SG|ELA|DV-UTU|DV-MINEN|N
SG|ESS|DV-JA|DV-TTA|N
SG|ESS|DV-JA|N
SG|ESS|N
SG|ESS|POS|PCP1|ACT
SG|ESS|kin|N
SG|FORGN|ESS|N
SG|GEN|DV-TTA|N
SG|GEN|N
SG|GEN|hAn|N
SG|ILL|DV-MINEN|N
SG|ILL|DV-NTA|3|N
SG|ILL|DV-NTA|N
SG|ILL|DV-NTI|N
SG|ILL|up|DV-NTA|N
SG|NUM|ABL
SG|NUM|ESS
SG|N|ABL|DA-US
SG|N|ABL|up|PROP
SG|N|ESS|up|PROP
SG|ORD|NUM|ADE
SG|ORD|NUM|ESS
SG|ORD|NUM|ESS|up
SG|up|ABL|ABBR
SG|up|ABL|N
SG|up|DV-MINEN|GEN|N
SG|up|DV-NTA|GEN|N
SG|up|DV-NTI|GEN|N
SG|up|ESS|ABBR
SG|up|ESS|N
SG|up|st-hi|GEN|N
S|FORGN
S|FORGN|up
TEMP|V|PAST|3|ACT|DV-U
TRA|3|INF1|DV-TTA|V
TRA|3|INF1|V
TRA|3|PL|N
TRA|3|SG|DV-JA|N
TRA|3|SG|N
TRA|3|up|SG|N
TRA|COP|3|INF1|V
TRA|DA-UUS|PCP1|N|PSS|PL
TRA|DA-UUS|SG|DV-MATON|N
TRA|DA-UUS|SG|N
TRA|DV-JA|PL|N
TRA|DV-US|SG|N
TRA|NUM|SG
TRA|N|PL|DA-US
TRA|N|SG|DA-US
TRA|ORD|NUM|SG
TRA|ORD|NUM|SG|up
TRA|PCP2|POS|3|PSS|SG
TRA|PL|N
TRA|PL|POS|PCP1|ACT
TRA|POS|PCP1|3|PSS|SG
TRA|POS|PCP1|DV-TTA|ACT|PL
TRA|POS|PCP1|DV-TTA|PSS|PL
TRA|POS|PCP2|ACT|DV-U|SG
TRA|POS|SG|PCP2|ACT
TRA|PRON|INTG|kOhAn
TRA|PRON|REL
TRA|PRON|SG|DEM
TRA|PRON|up|REL
TRA|PSS|PCP2|PL|POS
TRA|PSS|POS|PCP1|PL
TRA|PSS|SG|PCP2|POS
TRA|PSS|SG|POS|PCP1
TRA|SG|DV-JA|N
TRA|SG|DV-MINEN|N
TRA|SG|DV-NTA|N
TRA|SG|N
TRA|SG|POS|PCP1|ACT
TRA|st-cllq|DV-US|SG|N
TRA|st-cllq|SG|N
TRA|up|SG|DV-JA|N
TRA|up|SG|N
TrunCo
TrunCo|3|ADE|SG|N
TrunCo|ADE|SG|N
TrunCo|ALL|SG|N
TrunCo|DV-US|ELA|PL|N
TrunCo|DV-US|SG|GEN|N
TrunCo|DV-US|SG|ILL|N
TrunCo|ELA|PL|N
TrunCo|ELA|SG|N
TrunCo|GEN|PL|N
TrunCo|ILL|SG|N
TrunCo|NON-TWOL
TrunCo|SG|GEN|N
TrunCo|up
TrunCo|up|NON-TWOL
TrunCo|up|SG|GEN|N
V|3|ACT|INE|DV-ELE|INF2
V|INF3|ABE|DV-ILE
V|NULL
V|up|IMPV|SG2|DV-TTA|ACT
V|up|IMPV|SG2|kin|ACT
digit|ABBR
digit|ADE|PL|N
digit|ADE|SG|N
digit|ADE|SG|kin|N
digit|ADE|SG|up|N
digit|ALL|SG|N
digit|A|ALL|POS|PL
digit|A|ELA|SG|POS
digit|A|POS|PL|GEN
digit|A|POS|PL|NOM
digit|A|SG|ESS|POS
digit|A|SG|POS|GEN
digit|A|SG|POS|NOM
digit|A|SG|POS|PTV
digit|ELA|SG|ABBR
digit|ILL|SG|ABBR
digit|INE|SG|ABBR
digit|INE|SG|N
digit|NOM|SG|ABBR
digit|NOM|SG|ABBR|TrunCo
digit|NOM|SG|N
digit|NOM|up|SG|ABBR
digit|PTV|3|PL|N
digit|PTV|SG|ABBR
digit|PTV|SG|N
digit|SG|ABBR|GEN
digit|SG|ABL|ABBR
digit|SG|ABL|N
digit|SG|GEN|N
digit|up|SG|ABBR|GEN
kAAn|ADE|SG|DV-JA|N
kAAn|ADE|SG|N
kAAn|ILL|SG|N
kAAn|INF3|ABE|V
kAAn|SG3|ACT|COND|V
kAAn|SG3|ACT|PRES|V
kA|SG3|NEGV|C|COORD|V
kA|up|SG3|NEGV|C|COORD|V
kO|ACT|COND|PL1|V
kO|ACT|PL3|PRES|V
kO|PL3|up|NEGV|V
kO|SG3|ACT|COND|V
kO|SG3|NEGV|V
kO|SG3|up|NEGV|V
kin|ACT|PL1|PRES|V
kin|GEN|PL|N
kin|SG|GEN|N
roman|ALL|up|SG|ABBR
roman|INE|up|PL|N
roman|INE|up|SG|ABBR
roman|NOM|up|SG|ABBR
roman|NOM|up|SG|N
roman|PTV|up|SG|ABBR
roman|SG|up|ABL|ABBR
roman|up|SG|ABBR|GEN
roman|up|SG|GEN|N
st-cllq|3|INE|PL|N
st-cllq|3|NOM|SG|N
st-cllq|ACT|PL3|PRES|V
st-cllq|ADE|SG|N
st-cllq|ADE|SG|up|N
st-cllq|ALL|up|SG|N
st-cllq|ELA|SG|N
st-cllq|ELA|up|PL|N
st-cllq|ESS|PL|N
st-cllq|GEN|PL|N
st-cllq|ILL|PL|N
st-cllq|ILL|SG|3|N
st-cllq|ILL|SG|N
st-cllq|ILL|up|SG|N
st-cllq|INE|SG|N
st-cllq|INS|PL|N
st-cllq|NOM|PL|N
st-cllq|NOM|SG|N
st-cllq|NOM|SG|up|N
st-cllq|NOM|up|PL|N
st-cllq|PTV|PL|N
st-cllq|PTV|SG|N
st-cllq|PTV|SG|up|N
st-cllq|SG3|ACT|PRES|V
st-cllq|SG|ABL|N
st-cllq|SG|GEN|N
st-cllq|SG|NOM|DV-MINEN|N
st-cllq|up|INTJ
st-vrnc|INF3|ILL|V
st-vrnc|SG|GEN|N
up|1SG|V|ACT|INE|INF2
up|ABBR
up|ABL|N|3|PROP|PL
up|ABL|N|3|PROP|SG
up|ABL|PL|N
up|ACT|IMPV|PL2|V
up|ACT|PL1|PRES|V
up|ACT|PL2|PRES|V
up|AD-A
up|ADE|DV-JA|PL|N
up|ADE|SG|ABBR
up|DA-UUS|DV-VAINEN|N|PTV|SG
up|DA-UUS|N|3|INE|SG
up|DA-UUS|N|DN-LLINEN|PTV|SG
up|DA-UUS|N|DN-TON|SG|GEN
up|DA-UUS|PCP1|N|PTV|PSS|PL
up|DV-ELE|SG|GEN|N
up|DV-ILE|N|DV-U|PTV|PL
up|DV-ILE|N|DV-U|SG|GEN
up|DV-ILE|SG1|ACT|PAST|kin|V
up|DV-TTA|N|DV-U|PTV|DV-ELE|PL
up|ELA|DV-JA|PL|N
up|ELA|N|DV-U|DV-ELE|SG
up|ELA|PCP2|POS|PSS|PL
up|ELA|PCP2|POS|PSS|SG
up|ELA|SG|ABBR
up|ELA|SG|DV-JA|N
up|ESS|PCP2|POS|PSS|PL
up|ESS|PL|N
up|ESS|kAAn|PRON|DEM|SG
up|FORGN|SG|GEN|N
up|GEN|PL|N
up|ILL|N|3|PROP|SG
up|ILL|N|DV-MINEN|DV-U|SG
up|IMPV|SG3|V|DV-TTA|ACT
up|INE|ACT|INF2|V
up|INS|kin|PL|N
up|INTJ
up|NEGV|PL1|V
up|NEG|DV-TTA|PAST|V|PSS
up|NON-TWOL
up|NUM|SG|GEN
up|N|3|DV-MINEN|PTV|SG
up|N|DV-UTU|DV-MINEN|SG|GEN
up|N|DV-U|DV-ELE|SG|GEN
up|N|DV-U|INE|DV-ELE|PL
up|N|GEN|PL|DA-US
up|N|GEN|PL|PROP
up|N|PL|INS|PROP
up|N|SG|ABE|PROP
up|N|SG|GEN|DA-US
up|N|SG|GEN|PROP
up|N|SG|GEN|st-derog
up|N|SG|GEN|st-slang
up|N|kin|INE|PROP|SG
up|ORD|NUM|SG|GEN
up|PCP2|POS|3|PTV|DV-U|PSS|SG
up|PCP2|POS|3|PTV|PSS|SG
up|PCP2|POS|INE|PSS|SG
up|PCP2|POS|PSS|GEN|PL
up|PCP2|POS|PSS|SG|GEN
up|PCP2|POS|PTV|PSS|PL
up|PL1|V|ACT|DV-U|PRES
up|PL1|V|kO|ACT|PRES
up|PL2|V|kO|ACT|PRES
up|PL2|hAn|V|ACT|PRES
up|PL3|V|kO|ACT|PRES
up|PL3|V|kO|PAST|ACT
up|POS|PCP1|ACT|PTV|SG
up|POS|PCP1|ACT|SG|GEN
up|POS|PCP2|ACT|SG|GEN
up|PRON|ADE|SG|DEM
up|PRON|ELA|DEM|PL
up|PRON|ELA|SG|DEM
up|PRON|pA|DEM|INE|SG
up|PROP
up|SG1|V|ACT|DV-ELE|PRES
up|SG1|V|DV-TTA|ACT|PRES
up|SG1|V|PAST|ACT|DV-ELE
up|SG1|V|PAST|ACT|DV-U
up|SG1|V|kO|ACT|PRES
up|SG1|V|pA|ACT|PRES
up|SG1|st-cllq|V|ACT|PRES
up|SG3|V|ACT|DV-U|PRES
up|SG3|V|kO|ACT|PRES
up|SG3|V|kO|COND|ACT
up|SG|ABBR|GEN
up|SG|ABE|N
up|SG|GEN|N
up|TEMP|V|PAST|3|ACT
up|TEMP|V|PAST|3|ACT|DV-U
up|TRA|N|3|PROP|SG
up|TRA|PCP2|POS|3|PSS|SG
up|V|3|ACT|INE|INF2
up|hAn|ILL|N|3|PROP|SG
up|hAn|PRON|DEM|SG|GEN
up|hAn|SG3|V|ACT|PRES
up|st-arch|st-derog|N|SG|GEN
up|st-hi|GEN|PL|N
end_of_list
    ;
    my @list = split(/\r?\n/, $list);
    return \@list;
}



1;

=head1 SYNOPSIS

  use Lingua::Interset::Tagset::FI::Turku;
  my $driver = Lingua::Interset::Tagset::FI::Turku->new();
  my $fs = $driver->decode('n/com,sg,nom'); ###!!! finský příklad podstatného jména

or

  use Lingua::Interset qw(decode);
  my $fs = decode('fi::turku', 'n/com,sg,nom'); ###!!! finský příklad podstatného jména

=head1 DESCRIPTION

Interset driver for the Finnish tagset from the Turku Dependency Treebank.
Tag is a sequence of features separated by vertical bars.
There are just the feature values, not attribute-value pairs.

=head1 SEE ALSO

L<Lingua::Interset>,
L<Lingua::Interset::Tagset>,
L<Lingua::Interset::FeatureStructure>

=cut
